LBHackney-IT/lbh-income-api

Dockerfile
Gemfile
Gemfile.lock
README.md
app/models/universal_housing/araction.rb
app/models/universal_housing_record.rb
config/database_universal_housing.yml
config/initializers/universal_housing.rb
docker-compose.yml
spec/models/universal_housing_record_spec.rb

We need to be able to query Universal Housing to retrieve priority scores/bands and recommend user assignments. Have verified that this works in development using a test.

Connect to Universal Housing

---

app/controllers/my_cases_controller.rb
spec/controllers/my_cases_controller_spec.rb

We add controller specs so we will be confident making changes in future.

 Add controller spec for MyCasesController#sync

---

Gemfile
Gemfile.lock
config/database.yml

We inject database configuration using DATABASE_URL in all environments other than development and test.

Use MySQL in production and staging

---

Gemfile
Gemfile.lock
config/environments/staging.rb
config/newrelic.yml

New Relic will help us diagnose bottlenecks easier. Hard to tell what's causing such long page loads at the moment.
Can be easily swapped for a different APM platform if necessary, just want to get something in ASAP.
Environment variables for credentials have already been set up in ECS.

Add staging env and set up newrelic

---

Dockerfile
Gemfile
Gemfile.lock
docker-compose.yml

Meaning the sync will run daily without intervention.

Run delayed jobs in development, staging and production

---

.circleci/config.yml

Run migrations on deployment

---

.circleci/config.yml
Dockerfile

Believe New Relic isn't working correctly on staging because it's gem is in a :staging, :production group, and the application is being built with RAILS_ENV=development.

Bundle staging and production images with the correct RAILS_ENV

---

app/controllers/users_controller.rb
config/routes.rb
lib/hackney/income/stub_find_or_create_user.rb
lib/hackney/income/use_case_factory.rb
spec/controllers/users_controller_spec.rb

Endpoint to create users upon login.

Endpoint to find or create user

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb

ENV vars are set on staging and production already.

Set up Sentry

---

Dockerfile

FROM needs to be before setup.

invalid sequence in Dockerfile

---

app/jobs/application_job.rb
app/jobs/hackney/income/jobs/sync_case_priority_job.rb
app/jobs/hackney/income/jobs/sync_cases_job.rb
config/application.rb
config/environments/test.rb
config/feature_toggle.rb
lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb
lib/job_scheduler.rb
spec/config/feature_toggle_spec.rb
spec/hackney/income/jobs/sync_case_priority_job_spec.rb
spec/hackney/income/jobs/sync_cases_job_spec.rb
spec/lib/job_scheduler_spec.rb

- @StevenLeighton21 - Limit to a year of historic transaction history 
- @cob16 - require env var 'ENABLE_TENANCY_SYNC = true' to run snc jobs 
- Would like some sugestions where the FeachureToggle module should live (directory wise)

Limit payment history in sync

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

Add's brakeman to generate a report after full spec runs.

add brakeman

---

lib/hackney/income/sql_pause_tenancy_gateway.rb
spec/lib/hackney/income/sql_pause_tenancy_gateway_spec.rb
spec/lib/hackney/income/stored_tenancies_gateway_spec.rb

- move dates parsing to expect a uniform string (iso8601)

Stricter date parseing

---

app/controllers/action_diary_controller.rb
lib/hackney/income/send_email.rb
lib/hackney/income/send_sms.rb
lib/hackney/income/set_tenancy_paused_status.rb
lib/hackney/tenancy/add_action_diary_entry.rb
lib/hackney/tenancy/gateway/action_diary_gateway.rb
spec/controllers/action_diary_controller_spec.rb
spec/lib/hackney/income/send_email_spec.rb
spec/lib/hackney/income/send_sms_spec.rb
spec/lib/hackney/tenancy/action_diary_gateway_spec.rb
spec/lib/hackney/tenancy/add_action_diary_entry_spec.rb

depends on https://github.com/LBHackney-IT/LBHTenancyAPI/pull/104

remove action balance required param

---

config/initializers/sentry.rb
lib/sentry/sanatize_messages_processor.rb
spec/lib/hackney/income/send_manual_sms_spec.rb
spec/lib/sentry/sanatize_messages_processor_spec.rb

Sanatizes the sentry error handling with the custom sms/email messaging

Mr sanitize messages

---

app/controllers/my_cases_controller.rb
app/jobs/hackney/income/jobs/sync_cases_job.rb
lib/hackney/income/background_job_gateway.rb
lib/hackney/income/schedule_green_in_arrears_message.rb
lib/hackney/income/schedule_sync_cases.rb
lib/hackney/income/sql_tenancies_matching_criteria_gateway.rb
lib/hackney/income/use_case_factory.rb
lib/tasks/income/messages.rake
lib/tasks/income/sync.rake
spec/controllers/my_cases_controller_spec.rb
spec/hackney/income/jobs/sync_cases_job_spec.rb
spec/lib/hackney/income/schedule_green_in_arrears_message_spec.rb
spec/lib/hackney/income/schedule_sync_cases_spec.rb
spec/lib/hackney/income/show_tenancies_for_criteria_green_in_arrears_spec.rb
spec/lib/hackney/income/sql_arrears_message_gateway_spec.rb
spec/support/tenancy_helper.rb

- also renamed delayed jobs methods to include the word schedule

Rake task to schedule green in arrears messages

---

lib/hackney/income/send_manual_sms.rb
spec/lib/hackney/income/send_automated_email_spec.rb
spec/lib/hackney/income/send_manual_email_spec.rb
spec/lib/hackney/income/send_manual_sms_spec.rb
spec/support/stubs/dummy_gov_notify_gateway.rb
spec/support/stubs/stub_notifications_gateway.rb

- also cleaned up a stub a little bit

Use sms content in manual action diary enty

---

Gemfile
Gemfile.lock
app/jobs/hackney/cloud/jobs/save_to_cloud_job.rb
app/models/hackney/cloud/document.rb
config/cloud_storage.yml
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
db/migrate/20190212114317_create_documents.rb
db/schema.rb
lib/hackney/cloud/adapter/aws_s3.rb
lib/hackney/cloud/adapter/fake.rb
lib/hackney/cloud/storage.rb
lib/tasks/income/cloud_storage.rake
spec/hackney/cloud/jobs/save_to_cloud_job_spec.rb
spec/lib/hackney/cloud/adapter/aws_s3_spec.rb
spec/lib/hackney/cloud/adapter/upload_test.txt
spec/lib/hackney/cloud/storage_spec.rb
spec/rails_helper.rb

This Implement the upload of Docs into cloud with async upload (using delayed job queue).
Trello: https://trello.com/c/I4qmskwx/157-save-letter-async-upload
https://trello.com/c/iEyFdsoR/139-save-letter-1

157 save letter async upload

---

config/environments/staging.rb

This add the cloud storage adaptor for the staging env.
Without this we cannot test the fuctionality in staging.

Setup adaptor for staging env.

---

lib/hackney/pdf/templates/letter_1_template.erb
lib/hackney/pdf/templates/pdf_styles.css

Gov Notify no longer rejecting

Fix letter styles

---

config/routes.rb
config/routes/sidekiq.rb

dashboard/sidekiq under basic auth

web for Sidekiq and scheduler

---

README.md

Update Readme with some info about Cloudstorage and Kms

Update Readme with AWS/Kms info

---

app/jobs/hackney/income/jobs/request_precompiled_letter_state_job.rb
lib/hackney/income/use_case_factory.rb
lib/hackney/notification/enqueue_request_all_precompiled_letter_states.rb
lib/hackney/notification/request_precompiled_letter_state.rb
lib/schedules.rb
lib/schedules/request_all_precompiled_letter_states.rb
schedule.yml
spec/factories/document.rb
spec/hackney/income/jobs/request_precompiled_letter_state_job_spec.rb
spec/lib/hackney/notification/enqueue_request_all_precompiled_letter_states_spec.rb
spec/lib/hackney/notification/request_precompiled_letter_state_spec.rb

Polls GovNotify every n minutes for status changes of qualifying documents.

Polling for letter state changes

---

app/controllers/documents_controller.rb
config/routes.rb
lib/hackney/cloud/storage.rb
lib/hackney/letter/all_documents_use_case.rb
lib/hackney/letter/use_case_factory.rb
spec/controllers/documents_controller_spec.rb
spec/lib/hackney/cloud/storage_spec.rb

`GET` /api/v1/documents/
returns: 
```json
[
{
"id": 1,
"uuid": "12af7d9c-e875-4128-90d7-7ac753a88412",
"extension": ".pdf",
"metadata": "{\"user_id\":\"114\",\"payment_ref\":\"test_ref\",\"template\":{\"path\":\"lib/hackney/pdf/templates/letter_1_template.erb\",\"name\":\"Letter 1 template\",\"id\":\"letter_1_template\"},\"user_name\":\"Jim Bob\"}",
"filename": "12af7d9c-e875-4128-90d7-7ac753a88412.pdf",
"url": null,
"mime_type": "application/pdf",
"status": "uploading",
"created_at": "2019-03-27T16:57:49.175Z",
"updated_at": "2019-03-27T16:57:49.175Z",
"ext_message_id": null
},
{
"id": 2,
"uuid": "ec178335-f2ea-45de-89db-3a6b0e4732c8",
"extension": ".pdf",
"metadata": "{\"user_id\":\"114\",\"payment_ref\":\"test_ref\",\"template\":{\"path\":\"lib/hackney/pdf/templates/letter_1_template.e …
```

Show all documents

---

schedule.yml

sets messages to be consistently sent based off BST - Europe/London

Use Europe/London daylight savings

---

lib/hackney/pdf/generator.rb
spec/lib/hackney/pdf/generator_spec.rb

Gov notify failing when tables touch margin. Moving margins up slightly.

moves bottom margin up when columns hit bottom

---

lib/schedules/tenancy_sync.rb

Delays 5 times....
1 minute
2 minutes 
6 minutes 
24 minutes
120 minutes
... then dies if it reties are exhausted

make sync retry non-linear

---

lib/tasks/bau/case_totals.rake
lib/tasks/bau/reassign_case.rake

These are based on scripts posted into Slack.
Moving them to rake tasks to make them easier to run on the servers.

Add some rake tasks for BAU requests

---

app/controllers/documents_controller.rb
lib/hackney/cloud/storage.rb
lib/hackney/letter/all_documents_use_case.rb
spec/controllers/documents_controller_spec.rb
spec/lib/hackney/cloud/storage_spec.rb

It adds payment_ref filter to filter the documents
trello: https://trello.com/c/PbFUZGqU/203-add-payment-reference-url-to-document-view-page

add payment_ref filter to filter the documents

---

app/models/hackney/service_charge/letter.rb
lib/hackney/income/universal_housing_leasehold_gateway.rb
spec/controllers/letters_controller_spec.rb
spec/lib/hackney/pdf/preview_generator_spec.rb
spec/lib/hackney/pdf/preview_spec.rb

- Soraya and Guy have requested that address line 1 is required and 3 isn't 
- balance is being rounded to 2 decimal places 
- names and addresses are being stripped

fixing decimal places

---

lib/hackney/notification/enqueue_request_all_precompiled_letter_states.rb
spec/lib/hackney/notification/enqueue_request_all_precompiled_letter_states_spec.rb

fix checking state when document is accepted

---

lib/hackney/pdf/templates/layouts/sender_address.erb

Hi guys the phone number is unfortunately incorrect on the letter templates. It looks to be coming from this partial. Can we deploy please - once we're happy build has worked.

Updating phone number to correct number

---

lib/hackney/pdf/templates/pdf_styles.css

update style so it's always within the box

Fix address box validation

---

lib/hackney/income/universal_housing_leasehold_gateway.rb
spec/lib/hackney/income/universal_housing_leasehold_gateway_spec.rb

Reverts LBHackney-IT/lbh-income-api#185
Deploying this out to Staging again, as I suspect it failed the deploy last time we tried this.
Manually running on the staging database gives the expected results.

add support for multi-household properties (attempt 2)

---

lib/hackney/income/universal_housing_leasehold_gateway.rb
spec/lib/hackney/income/universal_housing_leasehold_gateway_spec.rb

This sets up an aliased tenancy prop ref for us to use directly

account for households having a different prop ref

---

lib/hackney/pdf/templates/letter_1_in_arrears_FH.erb
lib/hackney/pdf/templates/letter_1_in_arrears_LH.erb
lib/hackney/pdf/templates/letter_1_in_arrears_SO.erb
lib/hackney/pdf/templates/letter_2_in_arrears_FH.erb
lib/hackney/pdf/templates/letter_2_in_arrears_LH.erb
lib/hackney/pdf/templates/letter_2_in_arrears_SO.erb
lib/hackney/pdf/templates/pdf_styles.css

Details of copy can be found in the Trello card. There are no changes to the lessee address box so there should be no validation concerns.

Update copy in letter templates

---

.env.sample
.gitignore
README.md

Getting the project to boot up the first time needed to some extra information that wasn't obvious.
- Added `.env.sample` to help highlight the missing information
- Spelling
- Is this actually useful?

Improve README project setup

---

app/controllers/tenancies_controller.rb
lib/hackney/income/get_tenancy.rb
lib/hackney/income/sql_tenancy_case_gateway.rb
spec/controllers/tenancies_controller_spec.rb
spec/lib/hackney/income/sql_tenancy_case_gateway_spec.rb

- rename get_tenancy to find
- return 404 when tenancy is not found

refactor get tenancy 

---

app/models/hackney/cloud/document.rb
config/cloud_storage.yml
lib/tasks/bau/backfill_message_state.rake

Relates to Trello card: https://trello.com/c/55lZlnix/253-letters-stuck-on-uploaded-status

Create BAU rake task to address issue of sent letters require a manual update

---

db/migrate/20191014112745_add_patch_code_to_case_priorities.rb
db/schema.rb
lib/hackney/income/stored_tenancies_gateway.rb
lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb
spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb
spec/support/stubs/stub_criteria.rb

- Sync Patch Code from UH 
- To allow us to show which case is in which patch

Sync Patch Code

---

app/models/hackney/income/models/case_priority.rb
db/migrate/20191008164749_add_classification_to_case_priority.rb
db/schema.rb
lib/hackney/income/stored_tenancies_gateway.rb

Part two of:
https://github.com/LBHackney-IT/lbh-income-api/pull/213
once classifications have been calculated, this needs to be saved into the database

saving classifications

---

lib/hackney/income/stored_tenancies_gateway.rb
lib/hackney/income/view_my_cases.rb
spec/lib/hackney/income/view_my_cases_spec.rb

- Add classification to my cases for next recommended action
- So the front end can tell the user what to do next

Add case classification to my cases

---

app/controllers/my_cases_controller.rb
lib/hackney/income/stored_tenancies_gateway.rb
lib/hackney/income/view_my_cases.rb
spec/controllers/my_cases_controller_spec.rb
spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
spec/lib/hackney/income/view_my_cases_spec.rb
spec/support/stubs/stored_tenancy_gateway_stub.rb

Allow a user to filter a work tray by the next immediate action
So the user can filter how they want to view their work tray

Filter by classification

---

db/migrate/20191021141505_add_courtdate_to_case_priorities.rb
db/schema.rb
lib/hackney/income/stored_tenancies_gateway.rb
lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb
lib/hackney/income/view_my_cases.rb
spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb
spec/lib/hackney/income/view_my_cases_spec.rb
spec/support/stubs/stub_criteria.rb
spec/support/universal_housing_helper.rb

Fetch the `courtdate` from the tenagree table
So it can be sent to the frontend

Fetch courtdate from UH

---

db/migrate/20191022145325_add_court_outcome_to_case_priorities.rb
db/schema.rb
lib/hackney/income/stored_tenancies_gateway.rb
lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb
lib/hackney/income/view_my_cases.rb
spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb
spec/lib/hackney/income/view_my_cases_spec.rb
spec/support/stubs/stub_criteria.rb
spec/support/universal_housing_helper.rb

* As an Income Collection officer I need to record and view what the outcome of the court hearing was.
* Added court_outcome to the payload

Fetch court_outcome from uh

---

spec/rails_helper.rb
spec/requests/letters_spec.rb

- As a developer I need to have confidence my changes do not break things
- Add end-to-end specs for `LettersController#create` action
- Add end-to-end specs for `LettersController#send_letter` action

Add Request specs

---

app/models/hackney/service_charge/letter.rb
lib/hackney/pdf/templates/letter_before_action.erb
spec/models/hackney/service_charge/letter_spec.rb

**WHY**
As a user I want the LBA preview to display the correct information
**WHAT**
Typos fixed for LBA template and original lease date formatted.
Changes to wording within template

additional changes to LBA template

---

.gitignore

If we use Vim as our editor we need to ignore these files.

Add Vim files to gitignore

---

lib/hackney/income/stored_tenancies_gateway.rb
lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb
spec/lib/hackney/income/tenancy_prioritiser/band_spec.rb
spec/lib/hackney/income/tenancy_prioritiser/score_spec.rb
spec/lib/hackney/income/tenancy_prioritiser/tenancy_classification_spec.rb
spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb
spec/lib/hackney/income/tenancy_prioritiser_spec.rb
spec/support/stubs/stub_criteria.rb

- This was the root cause of the sync failing.
- Ensure we do not fall over this in the future.
- Update tests as we've removed the `writers`.

Ensure methods available in StubCriteria match Concrete implementation

---

lib/hackney/pdf/templates/layouts/financial_statement_lba.erb
lib/hackney/pdf/templates/layouts/payment_tables_lba.erb
lib/hackney/pdf/templates/layouts/reply_form_lba.erb
lib/hackney/pdf/templates/letter_before_action.erb
lib/hackney/pdf/templates/pdf_styles.css

As part of this ticket: https://hackney.atlassian.net/browse/MA-229?atlOrigin=eyJpIjoiYmQ4ODU2N2RkNTBkNDYzMWIxNzMzNWYzN2NjMjgxNjUiLCJwIjoiaiJ9
Needed to add a logo to the LBA letter, also made the forms more consistent.
Preview of what the letter now looks is bellow: 
[final_lba.pdf](https://github.com/LBHackney-IT/lbh-income-api/files/3846848/final_lba.pdf)

cleaner lba layout

---

lib/hackney/income/universal_housing_tenancies_gateway.rb
lib/hackney/income/use_case_factory.rb
spec/lib/hackney/income/universal_housing_tenancies_gateway_spec.rb

https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=MA&modal=detail&selectedIssue=MA-234

refactor: taking out restricted patches to allow syncing of all cases

---

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb
lib/hackney/tenancy/action_codes.rb
spec/lib/hackney/income/tenancy_prioritiser/tenancy_classification_spec.rb
spec/support/stubs/stub_criteria.rb

- As a User I need to know that I can apply for a court date for a case
- Add in the rule for the classification system

Add classification for PCOL/applying for court date as next action

---

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb
lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb
lib/hackney/tenancy/action_codes.rb
spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
spec/lib/hackney/income/tenancy_prioritiser/tenancy_classification_spec.rb
spec/support/stubs/stub_criteria.rb

- As a user I need to know when a NOSP is now actionable
- Add new rule to classification system

Add Actionable NOSP Classification

---

README.md

- We need to document this behaviour

Update README with how to setup scheduler

---

lib/hackney/pdf/templates/leasehold/letter_before_action.erb

**WHY**
- As a user I need to know that the LBA has the correct content on it.
**WHAT**
- Add new paragraph onto the LBA template

[MA-267] LBA content change

---

lib/hackney/pdf/templates/income/income_collection_letter_1.erb
lib/hackney/pdf/templates/income/income_collection_letter_2.erb
lib/hackney/pdf/templates/income/partials/payment_options.html.erb
lib/hackney/pdf/templates/pdf_styles.css

Changes requested for letters.
- Replaced template for letter 2 with the new version 
- [Google doc](https://docs.google.com/document/d/16fAdEMp7waNwS_0YQMbOytZCZ-3tEEJbbEYcTC3GB1U/edit)
- Added a payment options template 
- Now used in Income Collection Letters 1 and 2 
- [Google doc](https://docs.google.com/document/d/1ah_bJGHKBE_xdNmBK5LtnBkm3r0BlFosIfbPpa4cl68/edit?ts=5de62bca)
- Removed the dash from the arrears balance in Letter 1

[MA-253] Update Letter Templates

---

lib/use_cases/case_classification_to_letter_type_map.rb
spec/use_cases/automate_sending_letters_spec.rb
spec/use_cases/case_classification_to_letter_type_map_spec.rb

- We want fine control over which letters we can automate
- Use env variables to allow us to turn on/off each automated letter
- I found this helper function which is quite nice:  https://github.com/LBHackney-IT/lbh-income-api/blob/master/config/feature_toggle.rb

Add feature toggles for each automated rents letter

---

app/controllers/letters_controller.rb
spec/controllers/letters_controller_spec.rb

Allow letters controller to take a tenancy_ref
So we can write to the action diary

Allow send letter to take a tenancy_ref

---

lib/hackney/notification/send_manual_precompiled_letter.rb
lib/use_cases/automate_sending_letters.rb

Reduce system name size as the username size is limited to **40 characters!!!!!**
UH column has a max size of 40 characters

Reduce size of system user

---

.rubocop.yml
spec/lib/hackney/income/tenancy_prioritiser/classifications/apply_for_court_date_spec.rb
spec/support/shared_example_for_tenancy_classification.rb

@richrace and I talked about the best way to write these specs, and agreed that trying things out was the best way to tell if it made things clearer.
This PR attempts to make these specs more readable without losing the explanatory power of examples. It also does a little work on the output of those specs, attempting to express a high-level description of each case.
I'm totally happy to throw away this change if it doesn't help the readability.
_____
Old output:
New output:

DRY up court date examples

---

lib/hackney/income/universal_housing_income_gateway.rb
spec/lib/hackney/income/universal_housing_income_gateway_spec.rb
spec/requests/income_collection_letters_spec.rb
spec/support/universal_housing_helper.rb

the first line of address was not being pulled from UH correctly.

Rent letter address fix

---

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb
lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb
spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb
spec/support/stubs/stub_criteria.rb
spec/support/universal_housing_helper.rb

Gross rent is:
- Basic Rent
- Service
- Other Charges

Use gross rent rather than basic rent

---

lib/hackney/cloud/storage.rb
lib/hackney/notification/enqueue_request_all_precompiled_letter_states.rb
spec/lib/hackney/notification/enqueue_request_all_precompiled_letter_states_spec.rb

We received a sentry error where the `where` is not defined on `Hackney::Cloud::Storage`
Move the implementation onto that file

Fix error where using the wrong object

---

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb
lib/hackney/tenancy/action_codes.rb
lib/hackney/tenancy/court_outcome_codes.rb
spec/lib/hackney/income/tenancy_prioritiser/classifications/apply_for_outright_possession_warrant_spec.rb

**What?**
- Fix the action codes required for an outright possession 
**Why?** 
- The incorrect action codes were being used

Fix action codes for outright possession order

---

README.md

This PR adds documentation around how automation works and details on how to maintain and extend this feature

Add documentation around how automation works

---

lib/use_cases/automate_sending_letters.rb
spec/features/letter_automation/failing_validation_blocks_sending_letters_spec.rb
spec/lib/hackney/income/sql_legal_cases_gateway_spec.rb
spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb
spec/lib/hackney/income/universal_housing_income_gateway_spec.rb
spec/lib/hackney/income/universal_housing_leasehold_gateway_spec.rb
spec/lib/hackney/income/universal_housing_tenancies_gateway_spec.rb
spec/rails_helper.rb
spec/support/universal_housing_helper.rb
spec/use_cases/automate_sending_letters_spec.rb

**WHY**
- To ensure that letters messing mandatory fields are not sent by automation
**WHAT**
- Validation added to check if a generated letter has any errors on it

Letter validation before sending

---

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb
lib/hackney/tenancy/action_codes.rb
spec/lib/hackney/income/tenancy_prioritiser/classifications/apply_for_outright_possession_warrant_spec.rb

**What?**
- Add the action code which follows `apply for outright possession` 
**Why**
- Apply logic so it doesn't remain in this classification indefinitely

Add apply for warrant action code

---

app/controllers/documents_controller.rb
lib/hackney/cloud/storage.rb
lib/hackney/letter/all_documents_use_case.rb
spec/controllers/documents_controller_spec.rb
spec/lib/hackney/cloud/storage_spec.rb
spec/lib/hackney/letter/all_documents_use_case_spec.rb

users need to filter documents by status to quickly find failed letters

filter by document status

---

app/jobs/hackney/income/jobs/send_sms_job.rb
app/models/hackney/income/models/case_priority.rb
lib/hackney/income/background_job_gateway.rb
lib/hackney/income/schedule_send_sms.rb
lib/hackney/income/show_send_sms_tenancies.rb
lib/hackney/income/sql_tenancies_matching_criteria_gateway.rb
lib/hackney/income/use_case_factory.rb
lib/schedules/green_in_arrears_messages.rb
lib/schedules/send_sms_messages.rb
lib/tasks/bau/failed_messages_report.rake
lib/tasks/income/income.rake
lib/tasks/income/messages.rake
lib/use_cases/case_ready_for_letter_automation.rb
lib/use_cases/case_ready_for_sms_automation.rb
schedule.yml
spec/hackney/income/jobs/send_sms_job_spec.rb
spec/lib/hackney/income/background_job_gateway_spec.rb
spec/lib/hackney/income/schedule_send_sms_spec.rb
spec/lib/hackney/income/show_send_sms_tenancies_spec.rb
spec/lib/hackney/income/sql_tenancies_matching_criteria_gateway_spec.rb
spec/use_cases/case_ready_for_letter_automation_spec.rb
spec/use_cases/case_ready_for_sms_automation_spec.rb

We need to automate sending SMS to the SMS bucket
- Add env variables for feature flagging
- Add Cron job to send the SMS
- This is a separate automation than the sending of Letters (does not happen at sync time)

[MA-261] Enable SMS automation in code

---

app/jobs/hackney/income/jobs/add_action_diary_entry_job.rb
spec/hackney/income/jobs/add_action_diary_entry_job_spec.rb

Need to pause the case when automating SMS/Emails after writing to the action diary.

Need to pause cases after writing to action diary

---

README.md

This is getting me recruiter spam so would rater remove this

Remove myself from active maintainers

---

lib/hackney/income/tenancy_classification/classifier.rb
lib/hackney/income/tenancy_classification/v2/classifier.rb
spec/lib/hackney/income/tenancy_classification/classifier_spec.rb

Deviation logs are failing because of undefined variables
Fix unresolved references 
Are there any static analysis tools that would have caught this? Seems like a very obvious mistake that should have been picked up..
Fixes https://sentry.io/organizations/london-borough-of-hackney/issues/1708926871/?project=1276456&referrer=slack

Resolve undefined local variable

---

app/models/hackney/income/models/agreement.rb
app/models/hackney/income/models/agreement_state.rb
db/migrate/20200605100310_create_agreements.rb
db/schema.rb
spec/models/hackney/income/models/agreement_spec.rb

We want to allow CC/LCW's to be able to add an agreement so that tenants can repay their arrears over an agreed term. This is the first slice, to allow saving an agreement in the DB
- Create `agreements` table
- Add `Agreement` model and `agreement_type` and `frequency` constraints 
https://hackney.atlassian.net/browse/MAAP-171?focusedCommentId=15366

Create agreements table

---

lib/hackney/income/tenancy_classification/v2/classifier.rb
lib/hackney/income/tenancy_classification/v2/helpers.rb
lib/hackney/income/tenancy_classification/v2/rulesets/send_nosp.rb
spec/lib/hackney/income/tenancy_classification/classifier_spec.rb
spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb

Move send NOSP classification into it's own file and test related helpers
https://hackney.atlassian.net/browse/MAAP-201

Refactor rulesets send nosp

---

lib/hackney/income/tenancy_classification/classifier.rb

Add new log message to tell us if both classifiers match
* Add new log message to tell us if both classifiers match

Add log which checks if both classifiers match

---

lib/hackney/pdf/templates/income/income_collection_letter_1.erb

Changing the rent letter 1 template to include COVID message.
Before the change: 
------
After the change:
------
https://hackney.atlassian.net/browse/MAAP-229

update letter to include covid message

---

lib/hackney/pdf/templates/income/income_collection_letter_1.erb
lib/hackney/pdf/templates/income/income_collection_letter_2.erb

update rent letter 2 with covid message 
- update rent letter 2 with covid message 
- add payment options back into letter 1 template

update rent letter 2 with covid message 

---

app/models/hackney/income/models/agreement.rb
app/models/hackney/income/models/court_details.rb
db/migrate/20200715102014_add_formal_agreement_information.rb
db/schema.rb
spec/lib/hackney/income/create_agreement_spec.rb
spec/models/hackney/income/models/agreement_spec.rb
spec/models/hackney/income/models/court_details_spec.rb

We want to be able to record court details when creating formal agreements
Mobbing with @Ninamma @Miles-Alford 
- Add `court details` table and add association with formal agreements
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-332

Add court details table for creating formal agreements

---

lib/hackney/income/create_court_case.rb
spec/lib/hackney/income/create_court_case_spec.rb

We want to be able to create a court case to be able to create a formal agreement.
- Add a use-case for creating court case
https://hackney.atlassian.net/browse/MAAP-332

Add create court case use-case

---

app/controllers/court_cases_controller.rb

Realised when creating [this PR in the frontend](https://github.com/LBHackney-IT/LBH-IncomeCollection/pull/339) that I messed up the casing. 🙃

Forgot json needs camelcase

---

spec/requests/court_cases_spec.rb

See https://github.com/LBHackney-IT/lbh-income-api/pull/472
- Updated specs accordingly

Fix failing test in court cases requests spec after camel casing

---

app/models/hackney/income/models/case_priority.rb
lib/hackney/income/tenancy_classification/v2/classifier.rb
lib/hackney/income/tenancy_classification/v2/rulesets/address_court_agreement_breach.rb
spec/lib/hackney/income/tenancy_classification/rulesets/court_breach_no_payment_spec.rb
spec/lib/hackney/income/tenancy_classification/rulesets/send_breach_letters_spec.rb
spec/lib/hackney/income/tenancy_classification/rulesets/send_informal_agreement_breach_letter_spec.rb
spec/lib/hackney/income/tenancy_classification/rulesets/update_court_outcome_spec.rb

this action is getting renamed as there are several actions that need to be taken by the officer not just sending a letter
rename ruleset send_court_agreement_breach_letter to address_court_breach

add address_court_breach

---

lib/hackney/income/universal_housing_agreement_gateway.rb
spec/lib/hackney/income/universal_housing_agreement_gateway_spec.rb
spec/support/universal_housing_helper.rb

We need to be able to sync UH agreements into the MAA database. In order to do so we need a solid way of extracting agreements out of UH.
This PR adds a gateway that allows us to extract all agreements from UH, we can later loop over each of these and create agreements within MAA.
https://hackney.atlassian.net/browse/MAAP-224

Add UH agreement gateway

---

lib/hackney/income/migrate_uh_court_case.rb
lib/hackney/income/sync_case_priority.rb
lib/hackney/income/use_case_factory.rb
spec/lib/hackney/income/sync_case_priority_spec.rb

agreement sync part 1
hooking up the court case migrator to the sync

sync court cases

---

.rubocop.yml
lib/hackney/income/sync_case_priority.rb
lib/hackney/income/universal_housing_agreement_gateway.rb
lib/hackney/income/use_case_factory.rb
spec/lib/hackney/income/sync_case_priority_spec.rb

Time to migrate these agreements when we sync every night! 🌔 
Call migrate_uh_agreement usecase when syncing case priorities

Migrate agreements

---

.rubocop.yml
lib/hackney/income/sync_case_priority.rb
lib/hackney/income/universal_housing_agreement_gateway.rb
lib/hackney/income/use_case_factory.rb
spec/lib/hackney/income/sync_case_priority_spec.rb

Revert "Migrate agreements"

---

lib/hackney/income/update_agreement_state.rb

fix update state when no court date

---

spec/lib/hackney/income/update_agreement_state_spec.rb

Adding test for the court date check, sorry it took long - had to spend time trying to make rubocop happy 🙃

Add test for updating agreement when court case has no court date

---

app/models/hackney/income_collection/letter.rb
app/models/hackney/income_collection/letter/formal_agreement_breach.rb
lib/hackney/pdf/income_preview.rb
lib/hackney/pdf/templates/income/formal_agreement_breach_letter.erb
lib/use_cases/generate_and_store_letter.rb
spec/use_cases/generate_and_store_letter_spec.rb

[formal_breach_letter.pdf](https://github.com/LBHackney-IT/lbh-income-api/files/5156416/formal_breach_letter.pdf)
Added formal agreement breach letter

add formal agreement breach letter

---

app/models/hackney/income_collection/action.rb
db/migrate/20200916132752_migrate_action_metadata_to_json.rb
db/schema.rb
spec/models/hackney/income_collection/action_spec.rb
spec/requests/actions_spec.rb

the metadata column should be json, not text
add migration

action metadata column should be json, not text

---

lib/hackney/income/sync_case_priority.rb
lib/hackney/income/use_case_factory.rb
spec/lib/hackney/income/sync_case_priority_spec.rb

migrating the eviction date from uh into MA at sync 
https://hackney.atlassian.net/browse/MAAP-492

migrate eviction dates at sync

---

README.md

Update active maintainers on the readme

Update active maintainers on readme

---

lib/hackney/income/tenancy_classification/helpers/agreement_helpers.rb
spec/lib/hackney/income/tenancy_classification/rulesets/send_breach_letters_spec.rb

Fix for the referenced bug, other tightening on classification rules are coming
Allow a court agreement to start on the same day as the court date
https://hackney.atlassian.net/browse/MAAP-524

Allow a court agreement to start on the same day as the court date

---

CODEOWNERS

As we're now off the project, it doesn't make sense for us to receive the review requests
Remove MT users from CODEOWNERS

Remove MT users from CODEOWNERS
