LBHackney-IT/lbh-income-api

README.md, docker-compose.yml
Uses the new [Universal Housing simulator](https://github.com/LBHackney-IT/lbh-universal-housing-simulator) Dockerfile instead of the one in LBHTenancyAPI.
=> Connect to new UH simulator

Gemfile, Gemfile.lock, config/database_universal_housing.yml, lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, lib/hackney/income/universal_housing_tenancies_gateway.rb, lib/hackney/universal_housing/client.rb, spec/hackney/income/universal_housing_prioritisation_gateway_spec.rb, spec/hackney/universal_housing/client_spec.rb, spec/universal_housing_helper.rb
~**Don't review until https://github.com/LBHackney-IT/lbh-income-api/pull/6 is merged.**~
- SQL queries were using interpolated variables, which made SQL injection requests possible.
- Sequel has an adapter for TinyTds and provides a much nicer SQL client interface.
- Out of the box has parameter support!
=> Bind vars in SQL calls and use Sequel instead of TinyTds directly

app/controllers/my_cases_controller.rb, config/routes.rb, lib/hackney/income/tenancy_api_gateway.rb, lib/hackney/income/universal_housing_tenancies_gateway.rb, spec/hackney/income/tenancy_api_gateway_spec.rb
Cases would fail to sync due to Sequel mangling the database name on AWS but not locally. Add a fix to prevent this.
=> Resolve error when syncing cases

.circleci/config.yml
We add a new build step to circle config to add production deployments of lbh-income-api.
We also include another change to configure `ecs-deploy` timeouts via ENV:
`ecs-deploy` will timeout is a deploy does not complete within 90 seconds by default. It can take longer than this as we not only have to drain traffic from old deploys but also wait for ELB to deregister and register new applications. See here for more information: https://github.com/fabfuel/ecs-deploy/issues/14#issuecomment-277424439
We allow the timeout to be set via ENV in Circle as we've had issues of deploys taking more than 10 minutes to fully drain old tasks. Putting this in ENV will allow us to configure dynamically without changing the .circle/config.yml in future.
=> Add production deploy

Rakefile, app/controllers/application_controller.rb, app/controllers/my_cases_controller.rb, lib/hackney/income/use_case_factory.rb, lib/tasks/income.rake
We add rake task for syncing income collection cases to make it convenient to sync.
In order reduce chance of error we move construction of use cases into a factory.
We also needed to make a change to `Rakefile` to load an initialised version of the Rails application because the use case factory didn't autoload otherwise.
=> Add rake task for syncing income cases

spec/rails_helper.rb
Nearly ran the test suite against our development SQL Server, now preventing this outright.
=> Stop test suite if UH credentials do not look like the simulator

.circleci/config.yml, db/migrate/20180829140413_add_priority_factors_to_tenancies.rb, lib/hackney/income/dangerous_sync_cases.rb, lib/hackney/income/stored_tenancies_gateway.rb, lib/hackney/income/universal_housing_prioritisation_gateway.rb, spec/lib/hackney/income/dangerous_sync_cases_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/lib/hackney/income/universal_housing_prioritisation_gateway_spec.rb
Adds a set of score contributions to the tenancy model, to be persisted along with score and band.
Saved directly as the numerical contribution to the score to be provided as a breakdown, so we can say 'having an active NOSP contributed x of y to the score' etc. 
This means by default, the score contribution of 100.00 balance would be stored as +120.00 score contribution, which should help clarify how the different score values are reached and aid tweaking score generation through feedback > adjust weighting > feedback cycle.
=> Save priority factors

Gemfile, Gemfile.lock, app/jobs/application_job.rb, app/jobs/hackney/income/jobs/sync_cases_job.rb, bin/delayed_job, config/application.rb, config/environments/production.rb, config/initializers/schedule_jobs.rb, db/migrate/20180828112331_create_delayed_jobs.rb, db/schema.rb, lib/job_scheduler.rb, spec/hackney/income/jobs/sync_cases_job_spec.rb, spec/jobs/application_job_spec.rb, spec/lib/job_scheduler_spec.rb
- Syncs cases using the DangerousSyncCases use case.
- Runs daily at 3am. May need to amend this time, but fine for now I think.
- Schedules itself on completion, regardless of success.
- Fails without retrying at the moment, to avoid retries rolling over into normal daily operating hours.
- Logs errors.
=> Add daily sync cases job

lib/hackney/income/universal_housing_tenancies_gateway.rb, lib/hackney/income/use_case_factory.rb, spec/controllers/my_cases_controller_spec.rb, spec/lib/hackney/income/universal_housing_tenancies_gateway_spec.rb, spec/support/universal_housing_helper.rb
For our Beta team, we're going to start by only generating priority scores for tenancies in Beta patches. This should help us avoid performance issues making our sync job take too long in production, and reduce initial load on the database for a first test.
- Configures which patches are restricted via env vars.
- Will need to update env vars on staging and production before releasing.
=> Restrict tenancies used to beta patches when generating priority scores

Gemfile, Gemfile.lock, lib/hackney/income/tenancy_api_gateway.rb
Change has made the request go from 30+ seconds for a single tenancy ref, to subsecond for 30 tenancies.
=> Fix performance issue by removing rest-client and sticking to net/http

config/initializers/schedule_jobs.rb
To prevent this occurring whenever Rails is loaded without being served. e.g. to run migrations.
=> Only schedule jobs on app start, not on app load

.circleci/config.yml, Dockerfile
Runs a separate worker container for each environment on ECS, instead of running jobs and the application in the same container.
A) Fixes a bug where both _aren't_ running concurrently at the moment.
B) Means both can be stopped gracefully when ECS redeploys.
=> Fix concurrent tasks not running on ECS

.circleci/config.yml, Dockerfile
The RDS database can't be reached from Circle currently, temporarily running on the server instead.
=> Migrate on the server before deployment

lib/hackney/income/dangerous_view_my_cases.rb, spec/lib/hackney/income/dangerous_view_my_cases_spec.rb
We're currently having an issue on production where the my-cases API endpoint is failing, because tenancies which haven't been synced are being requested.
This should log a warning and skip the tenancy, so the user can see all the valid data we have without incomplete data.
Need to fix the sync to avoid this in future.
=> Hide cases if they haven't been synced into the API

app/models/hackney/income/models/user.rb, db/migrate/20180913132800_add_users.rb, lib/hackney/income/find_or_create_user.rb, lib/hackney/income/sql_users_gateway.rb, lib/hackney/income/stub_sql_users_gateway.rb, spec/lib/hackney/income/find_or_create_user_spec.rb, spec/lib/hackney/income/sql_users_gateway_spec.rb
WHAT 
Copy the find or create user use case and the sql users gateway from the ICS app to here. 
WHY
Next step will be to expose an endpoint allowing API consumers to create users directly. This will allow us to assign users to cases on the API, allowing consumers to request _cases_ for a given _user_.
The benefit of this is that we can control how and when user assignment is done, which will be when cases are synced from the data source.
=> Add find or create user and sql users gateway from ICS

app/controllers/my_cases_controller.rb, db/migrate/20180912114134_add_assigned_user_id_to_tenancies.rb, db/schema.rb, lib/hackney/income/dangerous_view_my_cases.rb, lib/hackney/income/stored_tenancies_gateway.rb, spec/controllers/my_cases_controller_spec.rb, spec/lib/hackney/income/dangerous_view_my_cases_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
For pagination with sorting to work efficiently, user assignment and priority scores should live in the same place. Previously, the Income Collection Service was aware of user assignment, but couldn't sort by priority score when retrieving user cases without fetching all of them. 
This also reduces the logic which will have to sit in the Income Collection Service, making it more easily reusable elsewhere.
=> Add user assignment to tenancies, and pagination to the my-cases endpoint

db/migrate/20180912114135_remove_assigned_user_id_from_tenancies.rb, db/schema.rb
This column was created as part of the pagination PR, and additionally as part of the users table creation PR. The latter got merged first, so it's left the schema in an inconsistent state.
Adding a migration between them to remove the former and leave the latter works locally.
=> Remove duplicate column creation

lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb
Seeing consistent performance improvements like this ^ when using `NOLOCK`. There should be no meaningful data integrity concern with this, as it's run out of hours.
=> Improve UH criteria performance using NOLOCK

app/models/hackney/income/models/tenancy.rb, lib/hackney/income/assign_tenancy_to_user.rb, lib/hackney/income/dangerous_sync_cases.rb, lib/hackney/income/sql_tenancy_case_gateway.rb, lib/hackney/income/use_case_factory.rb, spec/controllers/my_cases_controller_spec.rb, spec/lib/hackney/income/assign_tenancy_to_user_spec.rb, spec/lib/hackney/income/dangerous_sync_cases_spec.rb, spec/lib/hackney/income/sql_tenancy_case_gateway_spec.rb
Add use case that attempts to assign cases to the next available user, if the case is not already assigned.
Add the use case to the factory, call it for each synced tenancy.
=> Assign on sync

app/jobs/hackney/income/jobs/sync_case_priority_job.rb, lib/hackney/income/background_job_gateway.rb, lib/hackney/income/dangerous_sync_cases.rb, lib/hackney/income/sync_case_priority.rb, lib/hackney/income/use_case_factory.rb, spec/controllers/my_cases_controller_spec.rb, spec/hackney/income/jobs/sync_case_priority_job_spec.rb, spec/lib/hackney/income/background_job_gateway_spec.rb, spec/lib/hackney/income/dangerous_sync_cases_spec.rb, spec/lib/hackney/income/sync_case_priority_spec.rb
- The job running all cases in band is taking way too long. Giving it more time would be a poor fix, as four hours should be more than enough, and it would risk overlapping business hours.
- This updates the DangerousSyncCases use case to schedule a background job for each tenancy in arrears, so multiple workers can pick them up concurrently, rather than attempting to sync them all sequentially in the same job.
- Have been working on optimising the SQL separately, but conscious most of the bottleneck here is poor UH performance (and lack of parallelism.)
**Todo**
=> Sync cases as individual background jobs nightly (with assignment)

lib/hackney/income/stored_tenancies_gateway.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
The SyncCasePriority use case expects the StoredTenanciesGateway to return an ActiveRecord Tenancy object (this is not good, but we'll address later.) However, it's not being returned, so the user assignment logic is receiving the `update` call's `true` return value, rather than the `Tenancy` model.
=> Fix integration issue breaking assignment

app/models/hackney/income/models/user.rb, db/migrate/20180927140212_add_role_to_users.rb, db/schema.rb, lib/hackney/income/sql_tenancy_case_gateway.rb, spec/lib/hackney/income/assign_tenancy_to_user_spec.rb, spec/lib/hackney/income/sql_tenancy_case_gateway_spec.rb
What:
Add a role column to users and exclude users who do not have a role '1:credit_controller' from case assignment.
Why:
Currently assignment assigns cases evenly across all users, while some users in the system are devs/managers/legal case workers who will not need case assignment.
Future:
The income API needs some sort of management interface, and this interface will probably need to be able to modify the roles of users along with other management tasks like re-assigning cases manually.
=> Add user role column and exclude non-CC users from assignment

Dockerfile, bin/stack_test.rb
This is an attempt to fix `stack level too deep` when running the sql updates. The provided ruby `./bin/stack_test.rb`  should not throw an error if the env setup is successful.
TBD: if 5mb is enough
=> POC to update the stack level on the container

app/controllers/tenancies_controller.rb, app/models/hackney/income/models/tenancy.rb, config/routes.rb, db/migrate/20181010141355_add_pause_to_tenancies.rb, db/schema.rb, lib/hackney/income/set_tenancy_paused_status.rb, lib/hackney/income/sql_pause_tenancy_gateway.rb, lib/hackney/income/use_case_factory.rb, spec/controllers/tenancies_controller_spec.rb, spec/lib/hackney/income/set_tenancy_paused_status_spec.rb, spec/lib/hackney/income/sql_pause_tenancy_gateway_spec.rb, spec/lib/hackney/income/sql_tenancy_case_gateway_spec.rb, spec/support/tenancy_helper.rb
WHAT:
Add an endpoint that sets the new field on our persisted tenancy model, _paused status_ to the status given for the tenancy ref provided.
WHY:
We will need to use this status to determine if a tenancy should be displayed in a worktray, exempt from automation and potentially even more in future. The IC app will need some way to update this status.
=> Pause status

lib/hackney/income/dangerous_view_my_cases.rb, lib/hackney/income/stored_tenancies_gateway.rb, spec/lib/hackney/income/dangerous_view_my_cases_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
This is part of the work for view only paused tenancies.
- gateway takes an optional is_paused arg
- false filters on not paused
- true filters on only paused (anticipating future paused cases tab in frontend)
- same for usecase
PS I am not entirely happy with the the early returns in the use case howerver this change would fix a bug we am seeing on senchry production (and new tests).
=> Filter paused tenancies (gateway and usecase)

lib/hackney/income/migrate_patch_to_lcw.rb, lib/hackney/income/sql_legal_cases_gateway.rb, lib/hackney/income/use_case_factory.rb, lib/tasks/income.rake, spec/lib/hackney/income/migrate_patch_to_lcw_spec.rb, spec/lib/hackney/income/sql_legal_cases_gateway_spec.rb, spec/support/universal_housing_helper.rb
Added a rake task which allows manual migration of synced tenancies in a given patch to a given user ID.
Usage: `rake income:migrate_lcw_cases['patch',user_id]`
=> Migrate lcw worktray

config/initializers/delayed_job_config.rb
Config change that is keeping jobs from completing on production - delayed job is not handing threads for long running tasks appropriately and the 4hr timeout by default is causing long running syncs - This has a higher impact with less # of workers
=> HF config to handle default timeouts from 4hrs

config/database_universal_housing.yml
We are seeing thousands of timeouts over the course of the week on the legacy database. 
This PR doubles the timeout to 60 seconds and make a warning log line if a query gets past 45 seconds (so we know when we are getting close to our timeout). 
Potential DB load may actually decrease as queries are retried 10 times at the moment after a timeout.
=> Up UH timeout to 60sec from 30sec and log warn at 45

Gemfile, Gemfile.lock, app/controllers/action_diary_controller.rb, app/controllers/messages_controller.rb, config/routes.rb, lib/hackney/income/send_email.rb, lib/hackney/income/send_sms.rb, lib/hackney/income/sql_users_gateway.rb, lib/hackney/income/stored_tenancies_gateway.rb, lib/hackney/income/use_case_factory.rb, lib/hackney/tenancy/action_diary_gateway.rb, lib/hackney/tenancy/add_action_diary_entry.rb, lib/hackney/tenancy/exceptions/tenancy_api_exception.rb, spec/controllers/action_diary_controller_spec.rb, spec/controllers/messages_controller_spec.rb, spec/lib/hackney/income/send_email_spec.rb, spec/lib/hackney/income/send_sms_spec.rb, spec/lib/hackney/income/sql_users_gateway_spec.rb, spec/lib/hackney/tenancy/action_diary_gateway_spec.rb, spec/lib/hackney/tenancy/add_action_diary_entry_spec.rb
- API consumers can Post to `/tenancies/:tenancy_ref/action_diary`
- adds HTTPary as Gem
- Manual SMS/email writes to action diary (commented call/test out until action code agreed on)
=> add write to action diary route

app/controllers/action_diary_controller.rb, lib/hackney/income/use_case_factory.rb, lib/hackney/tenancy/add_action_diary_entry.rb, lib/hackney/tenancy/exceptions/tenancy_api_exception.rb, lib/hackney/tenancy/gateway/action_diary_gateway.rb, lib/hackney/tenancy/gateway/tenancies_gateway.rb, spec/controllers/action_diary_controller_spec.rb, spec/lib/hackney/income/tenancies_gateway_spec.rb, spec/lib/hackney/tenancy/action_diary_gateway_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
- This moves more of the tenancy API path into the app
- in particular, the '/api/v1' part so that v2 routes can be accessed
- the app now uses TENANCY_API_HOST and TENANCY_API_KEY (the old env vars can be removed once deployed)
- This fixes the ActionDiaryGateway that relied on using v2
=> Api version in app and action diary

Gemfile, app/controllers/application_controller.rb, config/initializers/filter_parameter_logging.rb, config/initializers/sentry.rb
sets up raven according to the docs and gains parity - `Raven 2.7.4 configured not to capture errors: DSN not set` for other environments.
Sanitises params with potentially identifiable data
=> Mr sanitizer

app/models/hackney/income/models/case_priority.rb, app/models/hackney/income/models/user.rb, db/migrate/20190114103101_rename_tenancies_to_case_priorities.rb, db/schema.rb, lib/hackney/income/assign_tenancy_to_user.rb, lib/hackney/income/sql_pause_tenancy_gateway.rb, lib/hackney/income/sql_tenancies_matching_criteria_gateway.rb, lib/hackney/income/sql_tenancy_case_gateway.rb, lib/hackney/income/stored_tenancies_gateway.rb, spec/lib/hackney/income/assign_tenancy_to_user_spec.rb, spec/lib/hackney/income/sql_arrears_message_gateway_spec.rb, spec/lib/hackney/income/sql_pause_tenancy_gateway_spec.rb, spec/lib/hackney/income/sql_tenancy_case_gateway_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/models/hackney/income/models/case_priorities_spec.rb, spec/support/tenancy_helper.rb
Step #1 in making tenancies generic enough to support cases
Renames the tables and cleans the relationships between models, gateways, etc.
Includes NO functional changes to the existing api.
=> Renaming tenancies to case priorities

lib/hackney/income/domain/notification_receipt.rb, lib/hackney/income/gov_notify_gateway.rb, lib/hackney/income/send_automated_sms.rb, spec/lib/hackney/income/domain/notification_receipt_spec.rb, spec/lib/hackney/income/gov_notify_gateway_spec.rb, spec/lib/hackney/income/send_automated_sms_spec.rb, spec/lib/hackney/tenancy/gateway/contacts_gateway_spec.rb, spec/support/stubs/stub_notifications_gateway.rb
~Do not merge until #104 is merged~
- GovNotifyGateway returns the "notification_receipt" domain object that contains the body of the sent message
- This is used to create the action diary message
=> Sms content in action diary

app/jobs/hackney/income/jobs/send_green_in_arrears_msg_job.rb, spec/hackney/income/jobs/send_green_in_arrears_msg_job_spec.rb
Add expiration to SendGreenInArrearsMsgJob.
If the job is older than 5 days, it raises an error and do not send the SMS.
Trello: https://trello.com/b/hCjSOWHF/hackney-ic-iteration-board
=> Add expiration to SendGreenInArrearsMsgJob

CODEOWNERS
This uses Github's [documented method](https://help.github.com/articles/about-code-owners/) of created default reviewers using a code owners file
=> Add default pr reviewers

Dockerfile, docker-compose.yml
Preserves the functionality when using makefile - but won't leave dangling containers on AWS
=> remove default running and rely on external

lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb
useful rename when reading the priority code.
changed code is tested here https://github.com/LBHackney-IT/lbh-income-api/blob/bc6662ff1f3d92506ac3595dd17a462804212315/spec/lib/hackney/income/stored_tenancies_gateway_spec.rb#L58
=> More descriptive sql var name used in loop

bin/delayed_job, lib/tasks/income/cloud_storage.rake
This PR
- Setup the `cloud_storage` to be processed
- Bug fix in the rake task
=> Add queue support for cloud storage + bug fix on cloud_storage.rake

Gemfile, lib/hackney/service_charge/gateway/service_charge_adapter.rb
I need faker to temporarily run in staging/production to demo letter generation, once we have a proper api endpoint faker will be exiled back into test only
=> faker temporarily moving into production

app/jobs/hackney/cloud/jobs/save_to_cloud_job.rb, config/cloud_storage.yml, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb, lib/hackney/cloud/adapter/aws_s3.rb, lib/hackney/cloud/adapter/fake.rb, lib/hackney/cloud/encryption_client.rb, spec/lib/hackney/cloud/adapter/aws_s3_spec.rb, spec/lib/hackney/cloud/encryption_client_spec.rb
This PR add the Client-Side encryption and support for KMS
(to know how it works read: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html)
Trello: https://trello.com/c/MfQ2yWRX/152-kms-envelope-encryption-implementation
=> Add support for KMS and client-side encryption

Makefile, docker-compose.local.yml, docker-compose.yml, spec/support/universal_housing_helper.rb
- the simulator now matches `uhlive` instead of `uhdev`
- removed the local reference (this will speed build time and ensure we are using the correct pinned version on local test runs)
=> Update uh simulator

lib/hackney/income/migrate_patch_to_lcw.rb, lib/tasks/income/income.rake
since the assignment of legal case workers fails when a case is not found and kills the whole process, this fix is not ideal but it will give you a list of not found tenancy refs
=> rescuing when tenancy is not found

app/controllers/documents_controller.rb, config/cloud_storage.yml, lib/hackney/cloud/storage.rb, spec/controllers/documents_controller_spec.rb, spec/lib/hackney/cloud/storage_spec.rb
This is a potential bugfix (discussed with @mrosel) for the plain white PDF generated on Staging env.
=> Potential Bug Fix for the plain white PDF bug.

app/models/hackney/service_charge/letter.rb, spec/controllers/letters_controller_spec.rb, spec/lib/hackney/pdf/preview_generator_spec.rb, spec/lib/hackney/pdf/preview_spec.rb
The preamble, that usually is the house name, should be optional (and most of the time is empty)
=> Make preamble optional

app/models/hackney/cloud/document.rb, lib/hackney/notification/enqueue_request_all_precompiled_letter_states.rb, lib/hackney/notification/request_precompiled_letter_state.rb, spec/lib/hackney/notification/enqueue_request_all_precompiled_letter_states_spec.rb, spec/lib/hackney/notification/request_precompiled_letter_state_spec.rb
1. documents weren't found because Gov notify uses its own ID which we mapped to `ext_message_id`
2.`'validation-failed` not just `failed`
=> matches the real failed value

lib/hackney/notification/manual_action_code.rb, lib/hackney/notification/send_manual_sms.rb, lib/hackney/tenancy/action_codes.rb, spec/lib/hackney/notification/manual_action_code_spec.rb
Originally I planned to do this using template IDs, however as there are multiple templates that can be sent, I've opted for a looser approach that will work so long as the current structure is sent.
A fallback happens to send the previous Manual SMS action code (which is `GMS`) when the template name can't be identified.
=> Get action codes for Manual SMSs based on the template name

lib/hackney/income/universal_housing_leasehold_gateway.rb, spec/lib/hackney/income/universal_housing_leasehold_gateway_spec.rb, spec/support/universal_housing_helper.rb
In case correspondence address is empty in the househ table, it make use of the property address.
=> Make use of prop address if corr address is empty

spec/controllers/messages_controller_spec.rb, spec/support/stubs/dummy_gov_notify_gateway.rb
This allows the dummy to give the name associated with the ID from the stub json.
=> make the dummy gov notify gateway able to give the expected name

lib/hackney/income/use_case_factory.rb, lib/hackney/notification/get_failed_sms_messages.rb, lib/hackney/notification/gov_notify_gateway.rb, lib/tasks/bau/failed_messages_report.rake, lib/tasks/bau/reassign_case.rake
This changes the manual process that depends on PaperTrail to directly use govnotify.
The current working logic is:
- Tenancy refs are always in the SMS Message ref
- Extract it out for known patterns
- dump the full SMS reference if it doesn't match a known pattern
- output the phone number and (optionally) the URL to the tenancy on the website.
=> add a task to generate failed message reports

lib/hackney/income/universal_housing_leasehold_gateway.rb, spec/lib/hackney/income/universal_housing_leasehold_gateway_spec.rb, spec/support/universal_housing_helper.rb
This includes a refactor to make our tests actually prove we're choosing between the household and property addresses correctly.
For actual behaviour changes, look at the individual commits
=> Use preamble and design from property address when no correspondence address is set

lib/hackney/income/universal_housing_leasehold_gateway.rb, spec/lib/hackney/income/universal_housing_leasehold_gateway_spec.rb
We need to look for the correspondence address based on the household reference.
We also need to use the property postcode as a base, instead of the household postcode
=> add support for multi-household properties

lib/hackney/income/universal_housing_leasehold_gateway.rb, spec/lib/hackney/income/universal_housing_leasehold_gateway_spec.rb
This needs a bit more work, and it's blocking the deploy to production.
Reverts LBHackney-IT/lbh-income-api#181
=> Revert "add support for multi-household properties"

app/jobs/hackney/income/jobs/add_action_diary_entry_job.rb, lib/hackney/tenancy/add_action_diary_entry.rb, lib/hackney/tenancy/gateway/action_diary_gateway.rb, spec/lib/hackney/tenancy/add_action_diary_entry_spec.rb, spec/lib/hackney/tenancy/gateway/action_diary_gateway_spec.rb
- add a new field (date) to the action diary gateway/use case.
- Action diary events can be backfilled when fixing errors (current priority)
- This is the groundwork for a longer-term fix of making add to action diary a background process.
The first step is to be able to add an entry using a given time. 
(This will then allow the task to be able to run in the background without delaying the time of the action diary event)
- gateway doc https://g6bw0g0ojk.execute-api.eu-west-2.amazonaws.com/production/tenancy/swagger/index.html?urls.primaryName=TenancyAPI%20v2
-  https://github.com/LBHackney-IT/LBHTenancyAPI/pull/113
=> Backdated action diary requests

README.md, lib/hackney/pdf/templates/pdf_styles.css
**What**
a) Very long Lessee full name is causing the letter to fail validation by Gov Notify. Have increased the max-width for this line. 
b) Reclaim some of the whitespace at the top of the envelope window box.
**Why**
a) Resolves validation issues
b) allows additional wrapping of up to two lines, at the cost of Lessee and Sender address blocks no longer being aligned.
=> Increase width of lessee address box

schedule.yml
An emergency workaround will revert back once issue with action diaries has been resolved.
=> Remove job from sched until issue has been fixed

db/migrate/20190930143533_add_rent_to_case_priority.rb, db/migrate/20191001160154_add_last_communication_action.rb, db/migrate/20191001160536_add_last_communication_date.rb, db/schema.rb, lib/hackney/income/stored_tenancies_gateway.rb, lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb, spec/support/stubs/stub_criteria.rb, spec/support/universal_housing_helper.rb
**What?**
-  Extracted weekly rent for tenancy from UH
- Saved this on income-collection db
- Extracted last_communication_action (code) from the araction table is UH
- Extracted last_communication_date from the araction table is UH
**Why?**
- To do weekly sync and calculate priority score
- Save last_communication_action and last_communication_date to income-api ab
=> Add weekly balance  and latest communication action and date to sync

lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb, spec/support/universal_housing_helper.rb
Instead of returning a `nil` UH returns `1900-01-01 00:00:00 +0000`
I didn't catch this the first time round while adding this to the sync, now I've added more tests and validation to save those dates as `nil`
=> Fix nil nosp date

lib/hackney/income/stored_tenancies_gateway.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
WHAT: Sort tenancies by balance
WHY: Users preferred working from descending arrears balances, rather that the priority.
=> Sort tenancies by balance

app/controllers/my_cases_controller.rb, lib/hackney/income/stored_tenancies_gateway.rb, lib/hackney/income/view_my_cases.rb, spec/controllers/my_cases_controller_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/lib/hackney/income/view_my_cases_spec.rb, spec/support/stubs/stored_tenancy_gateway_stub.rb
Now we are able to call 
GET `/api/v1/my-cases/?patch=W01` and get a worktray that is filtered by patch. 
The front end implementation of this is here https://github.com/LBHackney-IT/LBH-IncomeCollection/pull/215
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=MA&modal=detail&selectedIssue=MA-183
=> worktray to be filtered by patch

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, lib/hackney/tenancy/action_codes.rb, spec/lib/hackney/income/tenancy_prioritiser/tenancy_classification_spec.rb
We had implemented the classification rules without confirming which codes we should be checking. Now Elaine has provided accurate action diary codes that we should track. 
Please note that we still don't have a code for nosp warning letter - this still needs to be set up in UH
=> adjusting last communications codes

app/controllers/my_cases_controller.rb, lib/hackney/income/stored_tenancies_gateway.rb, spec/controllers/my_cases_controller_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
Added a query to filter the default view of the work tray
So not to show no_action in the immediate action tab
=> Add query to set default filter for worktray

lib/hackney/income/stored_tenancies_gateway.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
- As a user I need to filter the Worktray to the Patch I'm currently working on
- Add special filter for cases without a Patch
- How do we feel about the magic `'unassigned'` string that has to match the front end?
/cc @kjdchapman @bjpirt
=> Add filter for cases with unassigned Patch Codes

spec/requests/letters_spec.rb
Quick fix for failing tests due to missing values
=> Add missing values for hash

app/controllers/letters_controller.rb, app/jobs/hackney/income/jobs/send_letter_to_gov_notify_job.rb, db/migrate/20191101093146_add_columns_to_documents.rb, db/schema.rb, lib/hackney/cloud/storage.rb, lib/hackney/income/process_letter.rb, lib/hackney/letter/all_documents_use_case.rb, spec/controllers/letters_controller_spec.rb, spec/lib/hackney/income/process_letter_spec.rb, spec/lib/hackney/tenancy/add_action_diary_entry_spec.rb, spec/requests/letters_spec.rb
- So we can remove any reference to the User Model in a later change.
- Denormalise the User's Name and Email onto the Document Model. 
- Should wait for the large refactor (https://github.com/LBHackney-IT/lbh-income-api/pull/233) to be finished before merging this in.
- This change needs to be merged before https://github.com/LBHackney-IT/lbh-income-api/pull/235
=> Do not store User ID in metadata for Document

lib/hackney/pdf/templates/letter_before_action.erb
* Text size was too large
* Layout around the signature was broken
* Fixed formatting
=> Change text size and layout around signature image

db/migrate/20191106142526_add_eviction_date_to_criteria.rb, db/schema.rb, lib/hackney/income/stored_tenancies_gateway.rb, lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, lib/hackney/income/view_my_cases.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb, spec/lib/hackney/income/view_my_cases_spec.rb, spec/support/stubs/stub_criteria.rb, spec/support/universal_housing_helper.rb
* The evictdate field is required to notify the user of upcoming eviction dates for tenancies.
* Synced across tenagree.evictdate field from UH
* Added test
=> Fetch evictdate field from tenagree table

app/controllers/my_cases_controller.rb, lib/hackney/income/stored_tenancies_gateway.rb, spec/controllers/my_cases_controller_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb
Order cases with upcoming court dates
So the frontend can receive the cases in order of earliest upcoming court dates
=> Order by upcoming court date

Dockerfile
freetds.org website and ftp server went down. This is a workaround to 
ensure we can still develop and run our CI/CD pipeline.
=> Use Web Archive to download FreeTDS

.circleci/config.yml
- We need to deploy non-master branches to staging before we merge into master
- Add workflow to allow staging to be deployed manually.
=> Include a manual staging deploy from branches other than master

app/controllers/action_diary_controller.rb, lib/hackney/income/use_case_factory.rb, lib/use_cases/add_action_diary_and_sync_case.rb, spec/controllers/action_diary_controller_spec.rb, spec/use_cases/add_action_diary_and_sync_case_spec.rb
Added logic to commence a sync when a new action is added to a case
So we can have the most up to date data with regards to cases, instead of having to wait for the nightly sync
=> Commence a sync when adding a new action to a case

lib/hackney/income/use_case_factory.rb, lib/use_cases/add_action_diary_and_sync_case.rb, spec/use_cases/add_action_diary_and_sync_case_spec.rb
Originally called the `action_diary_gateway` which was incorrect as the `add_action_diary` usecase had an added stepped which was missed out in #250 
This PR fixes that issue
=> Call the add_action_diary not the gateway itself

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, lib/hackney/income/use_case_factory.rb, lib/tasks/income/sync.rake
- Add a Rake task that will sync tenancies inline
- Sometimes we want to manually run a sync. This gives us a nice interface via Rake rather than loading a Rails Console.
=> Add manual sync task

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, spec/lib/hackney/income/tenancy_prioritiser/tenancy_classification_spec.rb, spec/support/stubs/stub_criteria.rb
- When a NOSP has expired, classify the case as `send_NOSP` again
- Added more tests around `send_NOSP`
=> Support when NOSP expires classify case as `send_NOSP`

app/models/hackney/service_charge/letter/before_action.rb, app/models/hackney/service_charge/letter/letter_two.rb, spec/lib/hackney/pdf/get_templates_for_user_spec.rb, spec/models/hackney/service_charge/letter/before_action_spec.rb, spec/models/hackney/service_charge/letter/letter_two_spec.rb, spec/models/hackney/service_charge/letter_spec.rb, spec/requests/letters_spec.rb
**WHAT**
• Updated template paths for the LBA and letter 2, this is yet to be tested
• Update `lba_balance` calculation method
**WHY**
• LBA balance was not showing up as the directories of the templates has been updated so the correct letter class wasn't not picked up in the switch case
=> Fix LBA balance bug (MA-249)

app/jobs/hackney/income/jobs/send_letter_to_gov_notify_job.rb, app/models/hackney/cloud/document.rb, lib/hackney/cloud/storage.rb, spec/hackney/income/jobs/save_and_send_letter_job_spec.rb, spec/hackney/income/jobs/send_letter_to_gov_notify_job_spec.rb, spec/lib/hackney/cloud/storage_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/apply_for_court_date_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_nosp_spec.rb, spec/lib/hackney/notification/enqueue_request_all_precompiled_letter_states_spec.rb
Introduced a new state of `queued` to show that a letter has been queued up for sending to gov notify also users don't like seeing previews that were uploaded in the all documents page, so I've filtered them out.
=> Ma 248 letter saving bug

lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb
Similarly to court date and nosp dates, we get back a default-looking date (1st Jan 1900) if the field is missing in UH. This may be the fault of the tenancy API, or it may be the fault of MSSQL Server - either way, it's not desirable behaviour for us (as it confuses users and makes our classification logic harder).
In the future, it would be good to have this filtering in a single component rather than spread across multiple fields, but this PR should fix some significant issues with filtering, so I am happy to delay that cleanup.
=> Convert default (1900s) eviction date to 'nil'

lib/use_cases/case_ready_for_automation.rb, spec/use_cases/case_ready_for_automation_spec.rb
Allow the patch code list env variable to accept white spaces
To reduce fragility of the env variable
=> Allow patch code env list to take whitespaces

app/jobs/hackney/income/jobs/save_and_send_letter_job.rb, app/jobs/hackney/income/jobs/send_letter_to_gov_notify_job.rb, lib/hackney/notification/send_manual_precompiled_letter.rb, lib/use_cases/automate_sending_letters.rb, spec/hackney/income/jobs/send_letter_to_gov_notify_job_spec.rb, spec/lib/hackney/notification/send_manual_precompiled_letter_spec.rb
Pass the tenancy_ref through in the flow of automation
So it can write to the action diary once automation has sent letters 1 or 2
=> Allow automation of letters 1 and 2 to write to the action diary

lib/hackney/income/view_cases.rb, spec/lib/hackney/income/view_cases_spec.rb
patch codes where not returned when fetching all case priorities, this needs to be returned so that useful reports could be generated on the front end
=> return patch code in api

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_letter_two_spec.rb
Cases will only be classified as 'send letter two' if a letter one has already been sent, so that the letters are sent in order.
This PR changes the 'send letter two' classification to understand that an additional code (`SO1`) also means 'letter one has been sent'.
=> Add UH letter 1 as valid letter 2 precondition

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_letter_two_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_nosp_spec.rb, spec/support/stubs/stub_criteria.rb
This PR attempts to make the business rules around 'escaping' a particular classification, e.g.  
> if it's got an agreement on, don't send a NOSP.
This refactoring/exploration exposed some weird conditions/edge cases. This PR includes fixing the behaviour for these cases.
Notably, there is still duplication across each classification, the tests are hard to read, and other classification methods are still opaque. I hope to address these next.
=> Refactor (and fix) nosp/sms classification logic

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_court_warning_letter_spec.rb, spec/support/stubs/stub_criteria.rb
I've been looking at letter one/two/nosp classifications, and refactored some of these methods to try and get more clarity on the gaps (#282 and #283). 
This PR covers the rest of these methods. See individual commits for more detail about the steps I've taken.
I want to think more about how to clearly express "this policy applies to this subset of classifications", so I've pulled out the `paused?` check, but not `active_agreement?`.
I've also not made any significant changes to the test suite - I would like to try and make our examples more clear if we continue working on classifications.
=> Refactor classification methods

spec/support/shared_example_for_tenancy_classification.rb, spec/support/stubs/stub_criteria.rb
Some of these tripped me up whilst I was working in this area, so scout's code applies!
Most of these defaults aren't necessary for the specs to pass, but they do sometimes cause newly written specs to give false positives.
I wasn't able to remove some of the defaults as some tests do rely on them. Some of these specs are around unused functionality, but I didn't want to let the scope of this particular change grow.
I also removed an extra context block that wasn't necessary.
=> Remove classification stub defaults

app/models/hackney/income_collection/letter.rb, lib/hackney/pdf/templates/income/partials/tenant_address.html.erb, spec/lib/hackney/income_collection/letter_spec.rb, spec/lib/hackney/pdf/test_income_template.erb, spec/lib/hackney/pdf/translated_test_income_template.html, spec/lib/hackney/pdf/translated_test_income_template_with_blanks.html
appending empty lines to income collection letters so they pass gov notify validation
currently some address weren't passing validation because everything was brought up by one line
=> income collection letter template fix

lib/hackney/income/universal_housing_tenancies_gateway.rb, spec/lib/hackney/income/universal_housing_tenancies_gateway_spec.rb, spec/support/universal_housing_helper.rb
Some accounts in the `tenagree` table are sub-accounts of others, but we don't want to retrieve these (and we certainly don't want to do things like send them letters!).
Accounts that we do want to retrieve have a value of 'M' in tenagree.agr_type. There is a lookup table to give this value more semantic meaning, but joining onto this table probably gives us little long-term benefit (as we're using the database as the integration layer anyway).
Notably, this gateway is what we use for our 'sync', which pulls across all the cases we show in our various worktrays in the service.
This PR also includes a small bit of cleanup on the query, which passes the tests and shouldn't affect the raw SQL generated, it's just a little easier to read.
=> Only get master accounts from Universal Housing

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_court_agreement_breach_letter_spec.rb, spec/support/stubs/stub_criteria.rb
**What?**
- Remove stubbed date for latest active agreement date
- Add test which checks when latest active agreement date is nil
**Why?**
- Sync didn't run because the classifications wasn't handling a latest active agreement date of nil
=> Fix error on nil latest active agreement date

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_court_agreement_breach_letter_spec.rb
**What**
- Add test when the breach agreement date doesn't exit
- If all other conditions are met for a court ordered agreement but there is no date for when the agreement was breached, then it will still fall into the `send_court_agreement_breach_letter` bucket.
**Why?**
- So the sync can run without errors
=> Add test for no breach agreement date

lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb, spec/support/universal_housing_helper.rb
**What?**
- Update so that it is looking for `arag_startdate` instead of `arag_statusdate`
**Why?**
- The latest agreement date was incorrect, so the classifications were not  falling into the correct buckets
=> Fix latest agreement date field

lib/hackney/pdf/templates/leasehold/letter_before_action.erb
The LBA was generating an unnecessary empty page 
https://www.loom.com/share/11c4c54d80d04b078df9ee64b89423b9
=> removing unnecessary page break

app/controllers/documents_controller.rb, app/models/hackney/cloud/document.rb, config/routes.rb, lib/hackney/cloud/storage.rb, lib/hackney/income/use_case_factory.rb, lib/hackney/letter/review_failure.rb, lib/hackney/letter/use_case_factory.rb, lib/hackney/notification/request_precompiled_letter_state.rb, spec/controllers/documents_controller_spec.rb, spec/lib/hackney/cloud/storage_spec.rb, spec/lib/hackney/letter/review_failure_spec.rb, spec/lib/hackney/notification/enqueue_request_all_precompiled_letter_states_spec.rb, spec/lib/hackney/notification/request_precompiled_letter_state_spec.rb
this allows users to mark documents as 'failure_reviewed" once the govnotify validation issues have been resolved. 
This is done by ` post '/documents/:id/review_failure'` from the front end
=> Documents handling

schedule.yml
Payments are batch run at 19:45 in UH so give a good time for it to 
finish before we look at accounts.
=> Change the schedule to run after the payments have been processed

lib/hackney/cloud/storage.rb, spec/lib/hackney/notification/enqueue_request_all_precompiled_letter_states_spec.rb
exclude uploaded document from fetching gov notify statuses to prevent the following error from occurring 
https://sentry.io/organizations/london-borough-of-hackney/issues/1451931946/?project=1276456&referrer=slack
=> exclude uploaded document from fetching gov notify statuses

app/controllers/tenancies_controller.rb, app/models/hackney/income/models/case_priority.rb, lib/hackney/domain/nosp.rb, lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, spec/controllers/tenancies_controller_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb, spec/support/stubs/stub_criteria.rb
We have some complex logic so lets move it to be a Domain object that is easier to understand
Create a domain object and reuse it where we care about NOSPs
Once the Front End is updated to work with this new Object we should remove the fields we no longer care about on the Case Priority
- `nosp_expires_date`
- `active_nosp?`
- `nosp_served`
=> [MA-317] Refactor NOSP hash to object

app/controllers/documents_controller.rb, lib/hackney/cloud/storage.rb, lib/hackney/letter/all_documents_use_case.rb, spec/controllers/documents_controller_spec.rb, spec/lib/hackney/cloud/storage_spec.rb, spec/lib/hackney/letter/all_documents_use_case_spec.rb, spec/requests/downloading_a_letter_pdf_spec.rb
Calling `GET  /api/v1/documents?payment_ref=876147&page_number=1&documents_per_page=1`
will now return: 
```json
{
"documents": [{
"id": 1,
"uuid": "1eafd7b7-87fc-4a43-9fb2-37d3172f001a",
"extension": ".pdf",
"metadata": 
"{\"username\":\"Valentine Schoen\",\"email\":\"gus@buckridge.io\",\"payment_ref\":\"876147\",\"template\":{\"path\":\"lib/hackney/pdf/templates/leasehold/letter_before_action.erb\",\"name\":\"Letter before action\",\"id\":\"letter_before_action\"}}",
"filename": "1eafd7b7-87fc-4a43-9fb2-37d3172f001a.pdf",
"url": "blah.com",
"mime_type": "application/pdf",
"status": "downloaded",
"created_at": "2020-01-21T23:26:00.658Z",
"updated_at": "2020-01-21T23:26:00.658Z",
"ext_message_id": null,
"username": "Valentine Schoen",
"email": "gus@buckridge.io"
}],
"number_of_pages": 1, …
```
=> [MA-264] Pagination for View Letters page

app/controllers/tenancies_controller.rb, lib/hackney/income/stored_tenancies_gateway.rb, lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, spec/controllers/tenancies_controller_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/universal_housing_criteria_spec.rb, spec/support/stubs/stub_criteria.rb
- Only do one query to the `tenagree` table
- Rip out more attributes we do not use
- Uses `LEFT OUTER JOIN` as the `tenagree` might not always have a `property` (rare but lets keep the same behaviour as before)
Note: I have not removed the columns as I'm not 100% I can delete them. Due to not having good development data. We can deploy this to staging, see how it goes then add a migration to remove columns.
=> Refactor Criteria SQL statement

lib/hackney/cloud/storage.rb, spec/lib/hackney/notification/enqueue_request_all_precompiled_letter_states_spec.rb
`Downloaded` letters don't get sent to gov, so fetching the gov notify state raises an exception. 
https://sentry.io/organizations/london-borough-of-hackney/issues/1451931946/?project=1276456&query=is%3Aunresolved
=> exclude downloaded documents from requesting govnotify letter statuses

lib/hackney/income/universal_housing_tenancies_gateway.rb, lib/hackney/income/use_case_factory.rb, spec/lib/hackney/income/universal_housing_tenancies_gateway_spec.rb
There are some Tenancies with Patches like `WIC` that we do not care about so we should not sync them.
=> [MA-320] Only sync the patches we care about 

lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, schedule.yml
Sensible Time: 
- When the data import into the warehouse is finished + buffer time
- Gives us buffer time for more cases to use sync'd across (~6500 takes about 15min)
Also, ensured we are not Locking tables during the sync as this is a request from Hackney Support
=> Ensure Sync is run at a sensible time

.circleci/config.yml
So looking at the latest Prod deploy, here are our times for each EC2 instance being created/started:
Box 1:
```
Created at 2020-01-23 18:10:00 +0000
Started at 2020-01-23 18:10:32 +0000
```
Box 2: 
```
Created at 2020-01-23 18:39:18 +0000
Started at 2020-01-23 18:39:50 +0000
```
Box 3:
```
Created at 2020-01-23 18:48:58 +0000
Started at 2020-01-23 18:49:11 +0000
```
Using these times I've increased the timeout from Circle CI to be 50min. Not sure why the ECS is taking that long to deploy though.
=> Increase Timeout as we have seen long time deploys on AWS's end

lib/hackney/income/tenancy_prioritiser/tenancy_classification.rb, lib/hackney/income/tenancy_prioritiser/universal_housing_criteria.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_letter_one_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/classifications/send_letter_two_spec.rb, spec/lib/hackney/income/tenancy_prioritiser/tenancy_classification_spec.rb, spec/support/shared_example_for_tenancy_classification.rb, spec/support/stubs/stub_criteria.rb
We were previously not considering payments made within a week (the grace period) of the grace amount (1 week gross rent). Therefore, if someone was in small arrears (less than one weeks gross rent) it will not be shown correctly.
This change removes payments made in the week period from the grace amount, allowing us to calculate the correct grace amount.
E.g. 
Start of week 
- balance = 140
- rent = 100
- payments = 0
- grace = rent - payments -> 100
- arrears = balance - grace -> 40
After one payment
- balance = 100
- rent = 100
- payments = 40
- grace = rent - payments -> 60
- arrears = balance - grace -> 40
So if later in the week  if there's another payment 
- balance = 40
- rent = 100
- payments = 40 + 60 -> 100
- grace = rent - payments -> 0
- arrears = balance - grace -> 40
=> [MA-324] Be more clever with calculating grace amount

lib/hackney/income/stored_tenancies_gateway.rb, lib/hackney/income/view_cases.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/lib/hackney/income/view_cases_spec.rb
### Why
Users need to see pause_reason in their worktray
Return pause object with:
- reason, 
- comment
- until 
in the Cases payload
```
{
"cases": [
{
"ref": "0109179/01",
"current_balance": {
"value": 10797.16,
"currency_code": "GBP"
},
"current_arrears_agreement_status": null,
"latest_action": {
"code": "RMD",
"date": "2020-01-20T10:55:00.000Z"
},
"primary_contact": {
"name": "Ervin Koroglu",
"short_address": "140 Fletching Road",
"postcode": "E5 9QR"
},
"balance": "10797.16",
"days_in_arrears": 1780,
"days_since_last_payment": 1249,
"number_of_broken_agreements": 0,
"active_agreement": false,
"broken_court_order": false,
"nosp_served": false,
"active_nosp": false,
"courtdate": null,
"court_outcome": "   ",
"eviction_date": null,
"classification": "send_letter_two",
"patch_code": …
```
=> Return pause attributes in Cases payload

app/controllers/cases_controller.rb, lib/hackney/income/stored_tenancies_gateway.rb, spec/controllers/cases_controller_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/lib/hackney/income/view_cases_spec.rb
passing `pause_reason` to `/api/v1/cases` will now return a list of cases filtered by pause reason
=> filtering cases by pause reason

README.md
AWS CLI v2 no longer gives you the full shell script to log into the docker repository. It must be used along with the full docker login command.
The step for v1 was not complete and did not automatically execute the stdout from aws.
=> Reflect change in AWS commandline options

docker-compose.service.yml, docker-compose.yml
So `rails s` used to bind to `0.0.0.0`, but after 4.2 it binds to `localhost`.
Similar to [IncomeCollection](https://github.com/LBHackney-IT/LBH-IncomeCollection/commit/004b56a7b157bd31f2b446f94ef1c6cabf8e3743#diff-86d9fe5965e75841a04a67004e57730e), this just reverses that and was needed to get the API working locally.
😸
=> Stop default binding to localhost

spec/rails_helper.rb
Sidekiq is not processing jobs in test env, therefore showing a warning anytime we run the tests
- Remove Warning when running tests
=> Remove Sidekiq warning in test env

.circleci/config.yml, Gemfile, Gemfile.lock, Makefile, README.md, config/database.yml, db/schema.rb, docker-compose.service.yml, docker-compose.yml, lib/hackney/cloud/storage.rb, spec/controllers/tenancies_controller_spec.rb, spec/requests/income_collection_letters_spec.rb
In production/staging MySQL db is used by injecting the DB using the `DATABASE_URL` env var, while development and test environments are running SQLlite db. We want these env to be identical.
- Update docker-compose so we can run MySQL `db-development` and `db-test` in a separate container and inject them using `DATABASE_URL` 
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-117
=> Use mysql in dev and test env

.circleci/config.yml, config/database.yml, docker-compose.service.yml, docker-compose.yml
This is an issue when running `make run-all` using the [Frontend](https://github.com/LBHackney-IT/LBH-IncomeCollection). Both income-api and uh-simulator creates a db container with identical name, renaming solves the issue
Rename `db` container to `incomeapi-db`
=> Resolve container reference when running all services

.circleci/config.yml, Dockerfile, Makefile, README.md, bin/entrypoint.sh, docker-compose.service.yml, docker-compose.yml
With a separate MySQL container, the first time it boots it can take a
little while to populate the docker volume with the necessary data.
This will happen whenever the `dev_data` docker volume is removed.
* Add `dockerize`, a helper script that waits for services to
be connectable before allowing the service to start.
* Simplify the startup commands for the service.
* Auto create db if it doesn't already exist before migration.
All the above mean that every time you start the service using `docker-compose up` you'll get a database with all the right schema (whether it existed before or not).
See:
* https://github.com/jwilder/dockerize
* https://docs.docker.com/compose/rails/
Would be good to get another set of eyes on the Dockerfile, and docker-compose files.
I'm not sure if we'll want …
=> Wait for DB in development/test

bin/entrypoint.sh, docker-compose.service.yml, docker-compose.yml
Earlier today I merged #381 which had logic to run the following steps when the container was started:
* create a database in dev/test if it doesn't already exist
* migrate automatically
Running the migration automatically causes issues when multiple instances of the image are instantiated at the same time, since multiple migrations will be executed against the same database.
This happens when deploying to staging & production
See sentry error [ActiveRecord::ConcurrentMigrationError](https://sentry.io/organizations/london-borough-of-hackney/issues/1690594841)
* Remove automatic migration logic from entrypoint.
* Replace `db:create` with `db:setup`. The latter will load the schema so that the test/dev environment is ready to go when it loads.
* Restore migration command in docker-compose …
=> Resolve Sentry concurrent DB migration issue

lib/hackney/tenancy/gateway/action_diary_gateway.rb, spec/lib/hackney/tenancy/gateway/action_diary_gateway_spec.rb, spec/support/universal_housing_helper.rb
It was reported that usernames that are longer than 40 characters raises an exception on the tenancy api 
Proposing that we check the length of the username provided and if it's longer than 40 characters, change name to be `[first name]. [last name]`
https://hackney.atlassian.net/browse/MAAP-97?atlOrigin=eyJpIjoiNzY3YjRjYTRkZDIwNDE5ZmIwY2Q1MWE4MTVlYTM0NGMiLCJwIjoiaiJ9
=> if username is longer than 40, shorten it

spec/lib/hackney/income/classifications/send_nosp_spec.rb, spec/lib/hackney/income/universal_housing_criteria_spec.rb
Two send_nosp classification tests and two universal_housing_criteria tests were failing as they were testing that a NOSP was out of date. The test data specifically the date wasn't far back enough and as such the NOSP's were active causing the tests to fail
Where the test data had been 65 weeks ago I have replaced with adding on extra week to 66 making the NOSPS out of date
=> [FIX] Fix nosp related tests due to wrong date test data

lib/hackney/income/use_case_factory.rb, lib/use_cases/add_action_diary_and_pause_case.rb, spec/use_cases/add_action_diary_and_pause_case_spec.rb
When an sms is sent the case is automatically paused for a day to be resynced tomorrow, however if a user sends an sms/email to a customer in credit the case can not be paused as it is not in the worktray and this causes a sentry error. 
https://sentry.io/organizations/london-borough-of-hackney/issues/1623106077/?project=1276456
- Check if case is in a worktray before pausing the case
https://hackney.atlassian.net/browse/MAAP-204
=> check if case is in worktray before pausing after action diary was added

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/apply_for_outright_possession_warrant.rb, lib/hackney/income/tenancy_classification/v2/rulesets/base_ruleset.rb, lib/hackney/income/tenancy_classification/v2/rulesets/review_failed_letter.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb
We've identified a helper pattern that you can see in the code. My vision is that the helpers will be the only methods that each of the rulesets use, instead of directly querying the three objects as they do currently.
Once we've moved all the helpers, and added any additional helpers required, the helper methods should allow us to write DSL-like methods in the rulesets
* Introduce helpers file (TDD :tada:) to slowly migrate helpers into
* Decouple logic about whether ReviewFailedLetter is a valid action, and returning the action
* Refactor out Apply For Outright Possession Warrant into separate file
* Loop over array of classes to determine next actions
Does it feel like …
=> Classification refactor - Apply For Outright Possession Warrant

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_sms.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb
* Refactor out some helpers
* Refactor out Send SMS into separate file
* Sort ruleset by alphabet in order to ease git merge conflicts
[MAAP-201](https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&selectedIssue=MAAP-201)
=>  Classification refactor - Send SMS

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/rulesets/update_court_outcome_action.rb
"_Slowly slowly refactoring out the V2 engine into separate files, with goal of making the classification extensible_." - @antonyoneill 
- Refactor out **Update Court Outcome Action** into separate file
[MAAP-201](https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&selectedIssue=MAAP-201)
=> Move out UpdateCourtOutcomeAction logic from classifier

app/models/hackney/income/models/agreement.rb, app/models/hackney/income/models/agreement_state.rb, db/migrate/20200605100310_create_agreements.rb, db/schema.rb, lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/court_breach_visit.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_sms.rb, lib/hackney/income/tenancy_classification/v2/rulesets/update_court_outcome_action.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb, spec/lib/hackney/income/universal_housing_criteria_spec.rb, spec/models/hackney/income/models/agreement_spec.rb
Refactoring out the V2 engine into separate files allowing it to be more extensible when adding new classifications.
* Refactor helpers
* Refactor out Court Breach Visit classification into separate file
The tests which concern themselves with the agreement helpers would be good to look at, good to know if i'm going in the right direction with them
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-201
=> Classification refactor - Court Breach Visit

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_letter_one.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_letter_two.rb, spec/lib/hackney/income/tenancy_classification/classifier_spec.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb
- move letter one and two into separate ruleset files
- test helper methods
https://hackney.atlassian.net/browse/MAAP-201
=> move letter one and two into separate ruleset files

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_court_agreement_breach_letter.rb
Refactoring out the V2 engine into separate files allowing it to be more extensible when adding new classifications.
* Refactor out Send Court Agreement Breach Letter classification into separate file
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-201
=> Classification refactor - Send Court Agreement Breach Letter

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/court_breach_no_payment.rb, lib/hackney/income/tenancy_classification/v2/rulesets/court_breach_visit.rb, spec/lib/hackney/income/tenancy_classification/classifier_spec.rb
Due to uncertainty on how to test private action code helpers and to ensure consistency with other classification action code helpers, for now we have decided to remove the tests which test these helpers until we can find a better way to test these now private helpers.
* Refactor out valid_actions_for_court_breach_no_payment from helpers file into its associated classification file
* Refactor out court_breach_letter_actions from helpers file into its associated classification file
https://hackney.atlassian.net/browse/MAAP-226
=> Classification Refactor - Move action code helpers

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/informal_breached_after_letter.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb
Move informal breached after letter classification into it's own file and test helpers
https://hackney.atlassian.net/browse/MAAP-201
=> refactor informal breached after letter classification

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_court_warning_letter.rb, spec/lib/hackney/income/tenancy_classification/classifier_spec.rb
Refactoring out the V2 engine into separate files allowing it to be more extensible when adding new classifications.
* Refactor out Send Court Warning Letter classification into separate file
* Remove classifier tests for after_court_warning_letter_actions
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-201
For the removed tests:
https://hackney.atlassian.net/browse/MAAP-226
=> Classification refactor - Send Court Warning Letter

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_informal_agreement_breach_letter.rb
Slowly refactoring out the V2 engine into separate files, with goal of making the classification extensible.
Moved out the send informal agreement breach letter classification 
https://hackney.atlassian.net/browse/MAAP-201
=> refactor send informal agreement breach letter classification

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/rulesets/apply_for_court_date.rb, spec/lib/hackney/income/tenancy_classification/classifier_spec.rb
Refactoring out the V2 engine into separate files allowing it to be more extensible when adding new classifications.
Refactor out Apply For Court Date classification into separate file
Remove classifier tests for valid_actions_for_apply_for_court_date_to_progress
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-201
For the removed tests:
https://hackney.atlassian.net/browse/MAAP-226
=> Classification refactor - Apply For Court Date

app/controllers/agreements_controller.rb, app/models/hackney/income/models/agreement.rb, config/routes.rb, db/migrate/20200609111305_add_tenancy_ref_to_agreements_table.rb, db/schema.rb, lib/hackney/income/use_case_factory.rb, lib/hackney/income/view_agreements.rb, spec/lib/hackney/income/view_agreements_spec.rb, spec/models/hackney/income/models/agreement_spec.rb, spec/requests/agreements_spec.rb
We want to allow CC/LCW's to be able to view and create existing agreements so that tenants can repay their arrears over an agreed term. 
- Add endpoint to get existing agreements for tenancy
This is a basic implementation to GET `agreements` for a given `tanancy_ref` is there any case that's missing from tests?
https://hackney.atlassian.net/browse/MAAP-171?focusedCommentId=15366
=> Implement get agreements endpoint

lib/hackney/income/tenancy_classification/v2/classifier.rb
Old helpers which were already moved into the helper file were left on the V2 classifier file, these have been removed to get rid of the unused code and avoid confusion. 
* Remove case_has_eviction_date?, court_date_in_future? & case_paused? from V2 classifier file
=> Remove old helpers from V2 classifier

bin/entrypoint.sh
Few of us were receiveing an error when setting up the project:
```
ActiveRecord::EnvironmentMismatchError: 
You are attempting to modify a database that was last run in `test` environment.
You are running in `development` environment. 
If you are sure you want to continue, first set the environment using:
bin/rails db:environment:set RAILS_ENV=development
```
Thank you @antonyoneill for helping by sending this:
`docker-compose run --entrypoint='bin/rails db:environment:set RAILS_ENV=development' app`
The change sets the db environment to `development` which makes everything happy.
This fixes the issue I was having, but I still don't fully understand why this popped up - so if anyone could explain it like I'm 5, that might be good 😬
=> Set db env var to prevent environment mismatch

Dockerfile, Gemfile
We have a fairly significant issue in that we are unable to connect to Universal Housing from the income api.
I believe this is due to TLS cipher changes between the underlying base operating system provided by `ruby:2.5.3` and `ruby:2.7.1` in that the OS has changed from `stretch` to `buster`. 
The connection error that we have been witnessing has been described in this github issue https://github.com/rails-sqlserver/tiny_tds/issues/441 and I have been able to confirm locally that with stretch we are able to connect to UH.
* Temporary rollback of the ruby version upgrade from #388 
* I want to see the tests pass on this, as I'm not sure we've used any new syntax that would not be valid in 2.5.3.
=> Rollback Ruby for Debian Stretch

Gemfile.lock, app/controllers/agreement_response_helper.rb, app/controllers/agreements_controller.rb, db/migrate/20200630111144_add_created_by_to_agreements_table.rb, db/schema.rb, docs/api/v1/api.yaml, lib/hackney/income/create_agreement.rb, spec/lib/hackney/income/create_agreement_spec.rb, spec/lib/hackney/income/view_agreements_spec.rb, spec/models/hackney/income/models/agreement_spec.rb, spec/requests/agreements_spec.rb
Agreements details page show information about an agreement `created_by` and `created_at`, currently the API endpoints does not take or return these.
- Add migration to add `created_by` field to agreements table
- Update agreement use-cases and request to return these fields 
maybe?
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-173
=> Update get agreements response

app/controllers/agreements_controller.rb, app/models/hackney/income/models/agreement.rb, config/routes.rb, docs/api/v1/api.yaml, lib/hackney/income/cancel_agreement.rb, lib/hackney/income/create_agreement.rb, lib/hackney/income/use_case_factory.rb, spec/lib/hackney/income/cancel_agreement_spec.rb, spec/lib/hackney/income/create_agreement_spec.rb, spec/models/hackney/income/models/agreement_spec.rb, spec/requests/agreements_spec.rb
We want to allow caseworkers to cancel a live agreement
- Update API docs to add the new endpoint
- Add the `agreements/{id}/cancel` endpoint
- Refactor Agreements to check for any active state
- Update `create agreement` implementation so that we cancel all active agreements when creating a new agreement
Please before reviewing this have a look at this smaller PR https://github.com/LBHackney-IT/lbh-income-api/pull/418 
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-173
=>  Add cancel endpoint to agreements API

lib/hackney/service_charge/universal_housing_lease_gateway.rb, spec/lib/hackney/service_charge/universal_housing_lease_gateway_spec.rb, spec/support/universal_housing_helper.rb
Adding a service charge sync query to sync over one case (pt 2 of several)
- Added sql query that will identify what cases need to be queued up and processed by the _new_ service charge universal housing criteria (implemented in https://github.com/LBHackney-IT/lbh-income-api/pull/417)
- The main sql that identifies the cases is here: `lib/hackney/service_charge/universal_housing_lease_gateway.rb`
=> sql to identify what cases need to be synced

app/controllers/agreement_response_helper.rb, app/controllers/agreements_controller.rb, db/migrate/20200706144853_add_notes_to_agreements_table.rb, db/schema.rb, docs/api/v1/api.yaml, lib/hackney/income/create_agreement.rb, lib/hackney/income/use_case_factory.rb, spec/lib/hackney/income/create_agreement_spec.rb, spec/models/hackney/income/models/agreement_spec.rb, spec/requests/agreements_spec.rb
We want to be able to save notes and create a new action diary entry when a new agreement is created
- Add migration to add `notes` field to agreements table
- Update API docs
- Update agreement use-cases and request to return these fields 
- Refactor `create agreements` use case to use dependency injection for `cancel agreements`
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-173
=> Add notes field to agreements table

README.md, config/environments/development.rb
We may need to access the live worker in the future, I wanted to capture the steps to do so.
Also added config to make development environment emit log messages to aid debugging
* Update to README to contain info about prod access
* Add config to make logging out to stdout for income api in development environment
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-202
=> Add Production access note in README & Dev Env logging

lib/hackney/income/tenancy_classification/v2/rulesets/send_nosp.rb
We have a deviation on the new classifier whereby when a case has an empty court outcome, it prevents a NOSP being served.
The original ruleset did not reference the court outcome, and as such I do not believe the new ruleset should.
See
https://github.com/LBHackney-IT/lbh-income-api/commit/9c2811ec66186a54b35213a4918f1ea4b4cbdaa8#diff-2275c89af8d6aabdc8ee48871a213555L190-L202
for the original
* Remove court_outcome.blank? check from send_nosp
Hard to validate yourself, I've rerun the sync locally and it now matches the outcome matches the original MAA classification engine
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-202
=> Remove court_outcome check for send NOSP

app/models/hackney/income/models/agreement.rb, spec/models/hackney/income/models/agreement_spec.rb
As per design there are 4 possible payment frequencies when creating agreement:
- Add `4 weekly` and `fortnightly` frequencies to agreement model
=> Update payment frequenies on agreement model

lib/hackney/income/tenancy_classification/classifier.rb, lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/universal_housing_criteria.rb, spec/support/stubs/stub_criteria.rb
To aid in debugging classifier rules - at the moment the log output is not useful in identifying a tenancy.
Just a small one
* Emit a tenancy ref rather than a set of object hashes.
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-202
=> Expose tenancy_ref in classifier log

lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_nosp.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb
Continuing on with the deviation work. NOSP should not send if there's a court date in the past without a court outcome.
* Expect a court outcome to be set if there's a court date in the past.
=> Check court outcome and date for send nosp

lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_nosp.rb, lib/hackney/tenancy/court_outcome_codes.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb
The old classification engine had very loose rules. As a result we can trigger several actions for a given case, even though it should not.
Tighten the rules for sending NOSPs. In the this PR I have prevented a NOSP being sent if one of 6 court outcomes occurred within the last 6 years.
Technically some of them would have custom dates, but they are edge cases, and the dates are currently not stored in a normalised form in UH. Once we start modelling court outcomes and strike out dates then we can revisit.
Check if the send_nosp ruleset seems sensible to you, given the knowledge of the escalation process.
Incidentally, this resolves 19/21 deviations in this scenario. 1 of them is a potential out-of-date sync, and the other is a missing court outcome from the model "CDG". If you know what …
=> Check if active court warrant before sending nosp

lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_nosp.rb, lib/hackney/income/universal_housing_criteria.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb, spec/support/stubs/stub_criteria.rb
Resolving another deviation for the ruleset. Tightening the rules down so that a NOSP checks if there's an active agreement.
Use a more sophisticated check to see if an agreement is active - before this change it was only looking for agreements that had not been breached.
I'd like to refactor the existing `@criteria.active_agreement` out and make it all tidier, but I'm not sure about chasing this one down as it may have implications on the `stored_tenancies_gateway`. Maybe a q for @elena-vi 
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-202
=> Check agreement status before send nosp

bin/entrypoint.sh
When we tried to run 'make run-all' command from the front-end repo the Income API failed because the database didn't exist when we tried to setup the database environment
Made changes to the Entrypoint.sh if statement file so that it would run 'rails db:setup' before the database environment is set
May need to have a go at setting up from scratch to ensure this is the right fix
N/A
- If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- Environment variables have been updated
=> create database before set database environment

lib/hackney/income/view_agreements.rb, lib/hackney/income/view_court_cases.rb, spec/lib/hackney/income/view_court_cases_spec.rb
We want to be able to view the existing court cases to be able to retrieve formal agreements.
- Add a use-case for viewing court case
https://hackney.atlassian.net/browse/MAAP-332
=> Add view court cases use-case

lib/hackney/income/tenancy_classification/v2/rulesets/send_letter_one.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_sms.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_letter_one_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_sms_spec.rb
Investigate why the send_first_SMS rule is triggering given the following tag refs
Potentially checking if an active agreement already exists on the case
check if there is a breached non court ordered agreement
https://hackney.atlassian.net/browse/MAAP-333?atlOrigin=eyJpIjoiN2QzZTNhMDhiMTU3NDUwNzhhM2YzYmNlNDMyMjFiY2QiLCJwIjoiaiJ9
=> check if there is a breached non court ordered agreement

Makefile, app/controllers/court_cases_controller.rb, config/routes.rb, lib/hackney/income/use_case_factory.rb, spec/requests/court_cases_spec.rb
We want to be able to view existing court cases so we can view the court case of a formal agreement
- Add get court cases API endpoint
https://hackney.atlassian.net/browse/MAAP-332
=> Add GET court cases API endpoint

lib/hackney/income/tenancy_classification/v2/rulesets/send_letter_two.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_letter_two_spec.rb
There are deviations in the classifications from V1 and V2 of the classifier.
Add check for breached informal agreement before `send_letter_two` action
```
Expected: send_informal_agreement_breach_letter
Actual: :send_letter_two, :send_informal_agreement_breach_letter
Examples:
[
'005772/01',
'0101191/02',
'0101890/02',
'0102360/02',
'0102663/02',
'0103186/02',
'0103435/02',
'0103573/02',
'018349/01',
'023917/01'
]
```
https://hackney.atlassian.net/browse/MAAP-339?atlOrigin=eyJpIjoiNGM3MDczN2RjYjdkNDlhNWJhNzEzNWRhNWI1NWVkN2EiLCJwIjoiaiJ9
=> Check for breached informal agreement before sending letter 2

lib/hackney/income/create_agreement.rb, lib/hackney/income/create_formal_agreement.rb, lib/hackney/income/create_informal_agreement.rb, spec/lib/hackney/income/create_informal_agreement_spec.rb
As a formal agreement takes precedence over an informal agreement, when there is a active formal agreement on a tenancy, a caseworker should not be able to cancel that formal agreement by creating an informal one
- Add validation to `create_informal_agreement` use case to not cancel an active agreement if it is formal
- Update `cancel_active_agreement` method signature to now only accept active agreements 
https://hackney.atlassian.net/browse/MAAP-332
=> Implement Create Agreement Validation Rules

lib/hackney/income/stored_tenancies_gateway.rb, lib/hackney/income/tenancy_classification/classifier.rb, lib/hackney/income/tenancy_classification/v1/classifier.rb, lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/rulesets/base_ruleset.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_sms.rb, lib/hackney/income/use_case_factory.rb, spec/features/letter_automation/failing_validation_blocks_sending_letters_spec.rb, spec/features/letter_automation/syncing_spec.rb, spec/lib/hackney/income/stored_tenancies_gateway_spec.rb, spec/lib/hackney/income/tenancy_classification/classifier_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_letter_one_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_sms_spec.rb, spec/requests/manually_sending_a_letter_syncs_spec.rb, spec/support/shared_example_for_tenancy_classification.rb
we need to check if a case has a valid phone number before recommending the system to send sms
- check if there is a valid phone number in the sms ruleset
- allow the test suite to skip v1 classifier on some tests
=> Check phone number before recommending sms

README.md, lib/hackney/income/tenancy_classification/v2/helpers.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb
There is currently a case which V1 classifies as `no_action` but V2 classifies as `apply_for_court_date`.
Found that for V2, the helper function `balance_with_1_week_grace` uses `@criteria.balance`.
But it should use `@criteria.collectable_arrears` [as V1 does](https://github.com/LBHackney-IT/lbh-income-api/blob/f957bcdddd2c90afa1f13e4d1e105fc99fb1e7a2/lib/hackney/income/tenancy_classification/v1/classifier.rb#L257).
Also for a while I had an issue where while running all tests, UH simulator kept dying.
Turns out it was because I didn't have enough memory allocated for Docker, so I thought a little info about that in the README might be good.
- Make `balance_with_1_week_grace` use `@criteria.collectable_arrears` for V2
- Fix the test around this, using details from the case that is …
=> Use collectable arrears for v2 helper

lib/hackney/income/tenancy_classification/v2/rulesets/send_sms.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_sms_spec.rb
to avoid classifying cases as both send letter one and send sms we needed an upper limit
don't send sms if collectable arrears are more than £10
https://hackney.atlassian.net/browse/MAAP-359
=> add upper limit of £10 to sms rule

app/controllers/court_case_response_helper.rb, app/controllers/court_cases_controller.rb, app/models/hackney/income/models/court_case.rb, db/migrate/20200729112644_update_court_case_model.rb, db/schema.rb, lib/hackney/income/create_court_case.rb, spec/factories/court_case.rb, spec/lib/hackney/income/create_court_case_spec.rb, spec/lib/hackney/income/create_formal_agreement_spec.rb, spec/lib/hackney/income/create_informal_agreement_spec.rb, spec/lib/hackney/income/view_court_cases_spec.rb, spec/models/hackney/income/models/court_cases_spec.rb, spec/requests/court_cases_spec.rb, spec/support/shared_examples/create_agreement.rb
After the discussion around  and formal agreements, we realised we need to include `strike out date` and `created by` for court cases in the system.
- Add `strike out date` and `created by` to the CourtCase model
- Update usecases, controller and tests to work with this
=> Add strike out date and created by to court case model

lib/hackney/income/detect_breach.rb, spec/factories/agreement.rb, spec/lib/hackney/income/cancel_agreement_spec.rb, spec/lib/hackney/income/create_informal_agreement_spec.rb, spec/lib/hackney/income/detect_breach_spec.rb, spec/lib/hackney/income/view_agreements_spec.rb, spec/lib/hackney/income/view_court_cases_spec.rb, spec/models/hackney/income/models/agreement_spec.rb, spec/models/hackney/income/models/court_cases_spec.rb, spec/requests/agreements_spec.rb, spec/support/shared_examples/create_agreement.rb
We want to be able to detect whenever an informal agreement is breached. 
This is the first slice of tackling this problem and is not covering all the edge cases, simply just updates the agreement status to breached.
Next things to implement:
- Reset the agreement status to `live` when an agreement is no longer breached
- Add some info on why the breach is detected, e.g the UI design expects to show expected balance and actual balance and date of the last check, we should record these somewhere
- Add a corn job to run the process daily
- Add a use-case that can take an agreement and determine whenever its breached or not, based on its first instalment date(`start_date`), frequency of payment, the days of tolerance for completing the payment. 
When we discussed detecting breaches …
=> Add use-case to detect breaches in informal agreements

app/models/hackney/income/models/case_priority.rb, lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/rulesets/check_data.rb, lib/hackney/income/tenancy_classification/v2/rulesets/send_informal_agreement_breach_letter.rb, spec/lib/hackney/income/tenancy_classification/rulesets/apply_for_outright_possession_warrant_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/check_data_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/court_breach_no_payment_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_informal_agreement_breach_letter_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_nosp_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/update_court_outcome_spec.rb, spec/support/shared_example_for_tenancy_classification.rb
There are several wrong rules, and a few scenarios of bad data in UH.
V1 will start deviating significantly from this PR onwards.
This will also require an update to the frontend to display the Check Data action correctly, and probably will need an explainer somewhere to tell the officers exactly what it is they're meant to be checking, and give them an indication as to what it is that they can do to resolve.
- Added a ‘check_data’ action in the case that:
- A case has a court outcome but no court date
- A case is not paused, has a court date and court outcome but no agreement
- Updated send breached informal agreement letter if unless there is a valid nosp
Check logic seems right for the prioritisation. Might be easier to look per commit as they're atomic …
=> Implement check data action & Fix a few rules

app/models/hackney/income/models/agreement.rb, app/models/hackney/income/models/agreement_state.rb, lib/hackney/income/create_formal_agreement.rb, lib/hackney/income/create_informal_agreement.rb, lib/hackney/income/detect_breach.rb, spec/lib/hackney/income/cancel_agreement_spec.rb, spec/lib/hackney/income/create_informal_agreement_spec.rb, spec/lib/hackney/income/view_agreements_spec.rb, spec/models/hackney/income/models/agreement_spec.rb, spec/models/hackney/income/models/agreement_state_spec.rb, spec/requests/agreements_spec.rb, spec/support/shared_examples/create_agreement.rb
We monkey patched the `current_state` method on the `Agreement` model, to always look up and return the last agreement state, it’s not just inefficient but this can bite us later.
- Removed the monkey patch and update the `Agreement state` model to update the current state of an `Agreement` on creation
- Update test setups where needed
=> Update the `Agreement state` model 

app/controllers/court_case_response_helper.rb, app/controllers/court_cases_controller.rb, app/models/hackney/income/models/court_case.rb, db/migrate/20200803102320_update_court_case_column_names.rb, db/migrate/20200803165658_update_court_case_columns.rb, db/migrate/20200804143043_update_nullable_court_case_columns.rb, db/schema.rb, docs/api/v1/api.yaml, lib/hackney/income/create_court_case.rb, spec/factories/court_case.rb, spec/lib/hackney/income/create_court_case_spec.rb, spec/lib/hackney/income/create_formal_agreement_spec.rb, spec/lib/hackney/income/view_court_cases_spec.rb, spec/models/hackney/income/models/court_cases_spec.rb, spec/requests/court_cases_spec.rb
We want to allow officers in MA to be able to:
- Add a court case with _just_ the court date for a case/tenancy, before the actual court case takes place
- Add an outcome (and other details) for a court case that has taken place
We also want to allow for syncing of court outcomes in UH
- Some outcomes may not have a court date
- Some existing outcomes in UH won't map to our new list of court outcomes
- Updated documentation for court case end point:
- Added request body guidance
- Changed structure of court cases, removed `createdBy` and added `courtCaseHistory` to let us record the history of a court case, for example:
```
{
"id": 12,
"tenancyRef": "1",
"courtDate": "01/08/2020",
"courtOutcome": "Stay of execution",
"balanceOnCourtOutcomeDate": 1000,
"strikeOutDate": "01/08/2026", …
```
=> Update court case table and model

lib/hackney/income/sync_case_priority.rb, lib/hackney/income/use_case_factory.rb, lib/hackney/income/view_cases.rb, lib/hackney/income/worktray_item_gateway.rb, spec/controllers/cases_controller_spec.rb, spec/lib/hackney/income/sync_case_priority_spec.rb, spec/lib/hackney/income/view_cases_spec.rb, spec/lib/hackney/income/worktray_item_gateway_spec.rb
We want to use MAA agreements rather than the agreements from UH whenever we running classification, currently, the classifier called in the sync process, in `stored_tenancies_gateway` whenever a new `case_priority` is saved in the DB.
We want to refactor these responsibilities so we can update that agreement states in MAA before running the classifier and then saving a new worktray item(aka case priority) 
-  Rename stored_tenancies_gateway to  stored_worktray_item_gateway
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-176
=> Refactor SyncCasePriority 

lib/hackney/income/sync_case_priority.rb, lib/hackney/income/worktray_item_gateway.rb, spec/lib/hackney/income/sync_case_priority_spec.rb, spec/lib/hackney/income/worktray_item_gateway_spec.rb
We want to use MAA agreements rather than the agreements from UH whenever we running classification, currently, the classifier called in the sync process, in `stored_tenancies_gateway` whenever a new `case_priority` is saved in the DB.
We want to refactor these responsibilities so we can update that agreement states in MAA before running the classifier and then saving a new worktray item(aka case priority) 
This is the second slice of this refactoring, first slice: https://github.com/LBHackney-IT/lbh-income-api/pull/463
-  Call the classifier outside stored_tenancies_gateway during the sync process
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-176
=> Call the classifier outside stored_tenancies_gateway during the sync process

lib/hackney/income/tenancy_classification/v2/helpers.rb, lib/hackney/income/tenancy_classification/v2/helpers/uh_court_case_helpers.rb
We want to use MAA agreements rather than the agreements from UH whenever we running classification
- Move court_case helper methods to `UHCourtCaseHelpers` from `TenancyClassification::V2::Helper`, Once we synced agreements and court_cases from UH, we can swap these easily with a new module that uses the court cases in MA
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-176
=> Move court case related helper methods into a separate module

app/controllers/court_case_response_helper.rb, app/controllers/court_cases_controller.rb, config/routes.rb, lib/hackney/income/update_court_case.rb, lib/hackney/income/use_case_factory.rb, spec/lib/hackney/income/update_court_case_spec.rb, spec/requests/court_cases_spec.rb
For an officer, adding a court case is a 2 process step in the design, they:
1.  Add the court date (most likely before the court case takes place)
2. Add the outcome once the court case had taken place
I'm sorry it's so big 😭 - definitely could and should have sliced it into use case then endpoint... 😞 
- Adds an `update_court_case` use case that takes outcome information and updates an existing court case
- Adds a PATCH endpoint for updating an existing court case
To do:
- Update documentation for the endpoint (will do as I wait for this PR to be reviewed)
- In the controller, I separated required and optional parameters
- Is that unecessary or is having required params making things worse, since we will also check for required fields in the frontend
- I made the `update_court_case` use …
=> Allow updating court case

lib/hackney/income/tenancy_classification/v2/helpers/helpers_base.rb, lib/hackney/income/tenancy_classification/v2/helpers/ma_agreement_helpers.rb, lib/hackney/income/tenancy_classification/v2/helpers/ma_court_case_helpers.rb, lib/hackney/income/tenancy_classification/v2/helpers/uh_court_case_helpers.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/helpers_spec.rb, spec/lib/hackney/income/tenancy_classification/v2/helpers/ma_court_case_helpers_spec.rb
We want to use MAA agreements rather than the agreements from UH whenever we running classification
- Add agreements helpers for MA court cases `MACourtCaseHelpers`
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-176
=> Add ma court case helper

app/models/hackney/income/models/court_case.rb
It can fail a test when faker generates court_outcome that starts with 'a'
- Add tighter check for adjourned? on court case model
=> Add tighter check for adjourned? on court case model

config/routes.rb, spec/requests/court_cases_spec.rb
In the court case request test, we had the court_case `id` in the request body while in reality,
it is in the request path. This tripped me over when testing update court dates manually.
- Added some tests and updated the route with the correct param name.
=> Find court case id in path when updating a court case

lib/hackney/income/tenancy_classification/classifier.rb, spec/lib/hackney/income/tenancy_classification/classifier_spec.rb, spec/support/shared_example_for_tenancy_classification.rb
As the ruleset have been refactored, it's time phase out the old prioritiser/classifier 
phased out classification v1
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&selectedIssue=MAAP-202
=> Promote V2 secure tenancy classifier

app/controllers/agreements_controller.rb, lib/hackney/income/use_case_factory.rb, spec/requests/agreements_spec.rb
The create action on agreements controller calls `create informal agreement` use-case, we want to be able to create both based on request params
- Allow calling `create formal agreement` use-case when there is a `court case id` and :formal `agreement_type`
=> Allow creating both formal and informal agreements

lib/hackney/income/sync_case_priority.rb, spec/lib/hackney/income/sync_case_priority_spec.rb
There was a mistake when looking up agreements in `SyncCasePriority` use-case, instead of finding the last active agreement, the query returned the first matching agreement. 
- Add a test with multiple agreements 
- Update query to return the latest active agreement for the `tenancy`
=> Fix agreement query when syncing cases

lib/hackney/income/migrate_uh_court_case.rb, lib/hackney/income/use_case_factory.rb, lib/hackney/tenancy/updated_court_outcome_codes.rb, spec/lib/hackney/income/migrate_uh_court_case_spec.rb
We want to model court cases within MA. We're going to migrate the data in from UH on this so we can look up for formal agreements and allow officers to manage court cases through MA
Initial start on wiring up a court case migrator. It's responsibility is to determine whether it can/should create a court case in MA, and do so.
It will update court cases on subsequent syncs, provided there's only a single court case, and that it won't overwrite existing data on that single court case.
https://hackney.atlassian.net/browse/MAAP-417
=> Add uh court case migrator

app/models/hackney/income/models/court_case.rb, spec/factories/court_case.rb, spec/lib/hackney/income/create_court_case_spec.rb, spec/lib/hackney/income/create_formal_agreement_spec.rb, spec/lib/hackney/income/migrate_uh_court_case_spec.rb, spec/lib/hackney/income/view_court_cases_spec.rb, spec/models/hackney/income/models/court_cases_spec.rb, spec/requests/court_cases_spec.rb
Currently, there is no validation around `court outcome` in `CourtCase` model, this field is used in the classifier and in the breach detector, therefor allowing invalid court outcomes can cause issues. 
- Add validation around the `court outcome` field on the `CourtCase` model
- Change test setups where necessary
=> Add court outcome validation

app/models/hackney/income/models/court_case.rb, lib/hackney/income/create_court_case.rb, lib/hackney/income/migrate_uh_court_case.rb, lib/hackney/tenancy/updated_court_outcome_codes.rb, spec/factories/court_case.rb, spec/lib/hackney/income/migrate_uh_court_case_spec.rb
Synced fails because `CreateCourtCase` use-case expects `court_case_params`  as a keyword argument.
When we run `MigrateUhCourtCase` sometimes we map to the old court outcome codes, we shouldn't use these anymore, therefore I added the missing ones to the new court outcome codes. 
- Use keyword arg when calling `CreateCourtCase` use-case in `MigrateUhCourtCase`
- Use only the new court outcome codes in `MigrateUhCourtCase`
- Add the missing court outcome codes to the new court outcome codes
- When creating an `adjourned` court case in `MigrateUhCourtCase` default the `terms` and `disrepair_counter_claim` as the model has a validation for these
=> Fix court case sync and mapping

lib/hackney/income/universal_housing_agreement_gateway.rb, spec/lib/hackney/income/universal_housing_agreement_gateway_spec.rb
the universal housing agreements gateway wasn't working right  
passing in a live connection fixes the issue
=> refactor uh agreements gateway to receive a database connection

lib/hackney/income/tenancy_classification/v2/classifier.rb, lib/hackney/income/tenancy_classification/v2/rulesets/base_ruleset.rb, spec/support/shared_example_for_tenancy_classification.rb
We are using agreements data that is synced from UH when running classifier, going forward we want to use MA agreement system as the data source.
- Enable using MA agreements and court cases data in classifier
=> MERGE WHEN RELEASING AGREEMENTS - Enable using MA agreements and court cases data in classifier

lib/hackney/income/migrate_uh_agreement.rb, spec/lib/hackney/income/migrate_uh_agreement_spec.rb
- when there is a UH agreement and a court case we create a formal agreement
- when there are migrated agreements in the system, we ignore UH agreements
=> migrate uh agreement usecase

app/models/hackney/income/models/court_case.rb, lib/hackney/income/migrate_uh_court_case.rb, spec/factories/court_case.rb, spec/lib/hackney/income/create_court_case_spec.rb, spec/lib/hackney/income/create_formal_agreement_spec.rb, spec/lib/hackney/income/migrate_uh_court_case_spec.rb, spec/lib/hackney/income/update_court_case_spec.rb, spec/models/hackney/income/models/court_cases_spec.rb, spec/requests/court_cases_spec.rb
We now know that we need to ask the user about whether there's `terms` and a `disrepair counter claim` for additional court outcomes, not just adjourned ones.
This is the backend change to allow this to happen.
- Updated the court case model to validate for `terms` and `disrepair_counter_claim` for all relevant court outcomes
- Updated migration from UH and other tests accordingly
Maybe a double check that I got the correct court outcomes
https://hackney.atlassian.net/browse/MAAP-461?atlOrigin=eyJpIjoiYTgzMmNjYTEzYmZiNDFjM2FhZjc0OTE4ODZlMGEyMjEiLCJwIjoiaiJ9
=> Validate terms for more outcomes

app/controllers/letters_controller.rb, app/models/hackney/income_collection/letter/informal_agreement.rb, app/models/hackney/letter_date_helper.rb, lib/hackney/pdf/income_preview.rb, lib/hackney/pdf/templates/income/informal_agreement_confirmation_letter.erb, lib/use_cases/generate_and_store_letter.rb, spec/controllers/tenancies_controller_spec.rb, spec/factories/case_priority.rb, spec/lib/hackney/income_collection/letter_spec.rb, spec/lib/hackney/pdf/income_preview_spec.rb, spec/models/hackney/income_collection/letter/informal_agreement_spec.rb, spec/requests/income_collection_letters_spec.rb, spec/use_cases/generate_and_store_letter_spec.rb
The informal agreement confirmation letter template isn't 100% and it is not integrated with the preview generator.
- Fix missing and incorrect fields on the template
- Change generate_and_store_letter class to allow generating the preview 
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-370
=> Allow generating and storing informal agreement confirmation letters

.rubocop.yml, lib/hackney/income/create_agreement.rb, lib/hackney/income/migrate_uh_agreement.rb, lib/hackney/income/sync_case_priority.rb, lib/hackney/income/universal_housing_agreement_gateway.rb, lib/hackney/income/use_case_factory.rb, spec/lib/hackney/income/migrate_uh_agreement_spec.rb, spec/lib/hackney/income/sync_case_priority_spec.rb
Time to migrate these agreements when we sync every night! 🌔
- Call migrate_uh_agreement usecase when syncing case priorities
- make migrate_uh_agreement use the generic create agreement usecase
=> Enable agreements migration

app/models/hackney/income_collection/letter/informal_agreement_breach.rb, lib/hackney/pdf/income_preview.rb, lib/hackney/pdf/templates/income/informal_agreement_breach_letter.erb, lib/use_cases/generate_and_store_letter.rb, spec/lib/hackney/income_collection/letter_spec.rb, spec/use_cases/generate_and_store_letter_spec.rb
Informal agreement breach letter has not been added to `GenerateAndStoreLetter` templates so we cannot generate a letter preview for this template 
- Minor tweaks to the template 
- Allow generating the preview
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&modal=detail&selectedIssue=MAAP-371
=> Allow generating informal agreement breach letter preview

lib/hackney/income/view_cases.rb, lib/hackney/tenancy/gateway/tenancies_gateway.rb, spec/lib/hackney/income/universal_housing_criteria_spec.rb, spec/lib/hackney/income/view_cases_spec.rb, spec/lib/hackney/tenancy/gateway/tenancies_gateway_spec.rb
There is agreement data we pull from UH and rendered on `ViewCases` response. Going forward we should show agreement data that is pulled from MA. 
- Use MA agreements when rendering `current_arrears_agreement_status` for a work tray item
- Remove `current_arrears_agreement_status` when pulling tenancies from UH(we don't need this anymore)
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-421
=> Update current_arrears_agreement_status field on ViewCases response

lib/hackney/income/tenancy_classification/v2/helpers/ma_agreement_helpers.rb
We run into an error after migrating agreements and court cases from UH.
[Court date is nil when checking for breaches](https://sentry.io/organizations/london-borough-of-hackney/issues/1863378649/?project=1276456&referrer=slack) 
Check if court date is present before comparing to see if it has passed
=> Fix for when there's not court date (from UH)

app/models/hackney/income/models/court_case.rb, lib/hackney/income/worktray_item_gateway.rb, spec/lib/hackney/income/view_cases_spec.rb, spec/lib/hackney/income/worktray_item_gateway_spec.rb, spec/models/hackney/income/models/court_cases_spec.rb
There are `court_case` and `court_date` fields on `CasePriority` model, which is currently synced from UH. To show accurate data to the users, we want to show the `CourtCase` data that lives and managed in MA. 
- Change `CourtCase` to update related `CasePriority` whenever a court case created or changed
- Use court case data from MA when syncing case priorities 
I went down a miserable route and tried to remove `courtdate` and `court_outcome` fields from `CasePriority` model, but these are used when filtering tenancies, so we'd need to make changes in `WorktrayItemGateway` to be able to filter tenancies by `Upcoming Court Dates`.
By updating `CasePriority` whenever a court case created allows us to preserve the existing behaviour with the minimum change, also better for optimisation when …
=> Fix court case fields on CasePriority

app/models/hackney/income/models/agreement.rb, db/migrate/20200903143523_add_variable_payment_agreement_fields.rb, db/schema.rb, spec/factories/agreement.rb, spec/models/hackney/income/models/agreement_spec.rb
As a caseworker, I want to be able to enter an initial payment amount and date, so I can enter court agreements that have a larger first payment that followed by frequent smaller payments.
This is the first slice of allowing caseworkers to create `variable payment agreement `
- Add `initial_payment_amount: initial_payment_amount` and `initial_payment_date` fields to agreement table
- Add validation to agreement model and `variable_payment?` helper method
- Update factories  
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-464
=> Allow creating variable payment agreement 

app/models/hackney/income/models/agreement.rb, lib/hackney/income/update_agreement_state.rb, spec/lib/hackney/income/update_agreement_state_spec.rb, spec/models/hackney/income/models/agreement_spec.rb
add new frequency to allow for smoother agreement migration from UH
- added `unsupported_legacy_frequency` frequency
- make frequency required
- make the breach detector ignore agreements with `unsupported_legacy_frequency`
=> add new frequency to allow for smoother agreement migration from UH

lib/hackney/income/migrate_uh_agreement.rb, spec/lib/hackney/income/migrate_uh_agreement_spec.rb
UH is weird and wonderful and agreements have all sorts of frequencies, and we only support half of them. 
The following PR depends on https://github.com/LBHackney-IT/lbh-income-api/pull/515 being merged in
- when an agreement with an unsupported frequency is migrated, we set the frequency to [`unsupported_legacy_frequency `](https://github.com/LBHackney-IT/lbh-income-api/pull/515) and write a comment about what the frequency used to be 
- when a live agreement with an unsupported frequency, we raise a error what will be captured by sentry so that officers can amend the case accordingly in UH before we sync 
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&modal=detail&selectedIssue=MAAP-469
=> when uh frequency is not in MA, write a comment about what it was

.github/PULL_REQUEST_TEMPLATE.md, spec/models/hackney/income/models/agreement_spec.rb
Last Friday we had a minor outage when deployed a DB migration that dropped a field from DB. It's generally a good practice not to deploy a DB migration and code that relies on this migration in the same PR. 
- Update PR template with guidance for DB migration
=> Update PR template

app/controllers/agreement_response_helper.rb, app/controllers/agreements_controller.rb, docs/api/v1/api.yaml, lib/hackney/income/create_agreement.rb, lib/hackney/income/create_formal_agreement.rb, lib/hackney/income/create_informal_agreement.rb, spec/requests/agreements_spec.rb, spec/support/shared_examples/create_agreement.rb
As a caseworker, I want to be able to enter an initial payment amount and date, so I can enter court agreements that have a larger first payment that followed by frequent smaller payments.
This is the second slice, allowing agreement endpoints to create and retrieve variable payment agreement
- Update create agreement use-cases
- Allow variable payment params when calling create agreement endpoint
- Allow retrieving a variable payment agreement
- Update API docs
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-464
=> Allow agreement endpoints to create and retrieve variable payment agreement

lib/hackney/income/worktray_item_gateway.rb
We we're saving and displaying just the rent on letters, but we should be displaying the rent value as `rent + other charges` aka what the tenant needs to pay.
save gross rent as weekly rent
=> save gross rent (rent + other charges)

lib/hackney/pdf/templates/income/informal_agreement_confirmation_letter.erb
Full agreement data wasn't being displayed properly 
show agreement frequency correctly on letter
=> amend agreement confirmation letter

lib/hackney/income/update_agreement_state.rb, spec/lib/hackney/income/update_agreement_state_spec.rb
As a caseworker, I want to be able to enter an initial payment amount and date, so I can enter court agreements that have a larger first payment that followed by frequent smaller payments.
This is the third slice, allowing the breach detector to detect breached variable payment agreements
- Extend `UpdateAgreementState` to check whether the `initial_payment`(one-off payment before recurring payments) has been made
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-464
=>   Update breach detector to handle variable payment agreements

app/controllers/agreements_controller.rb, lib/hackney/income/create_formal_agreement.rb, spec/support/shared_examples/create_agreement.rb
When a formal agreement is created we need to make sure that the starting balance is the same as the balance at the court outcome
use the court outcome balance when creating a formal agreement
=> Use courtoutcome balance for formal agreements

app/models/hackney/income/models/agreement.rb, spec/factories/agreement.rb, spec/lib/hackney/income/update_agreement_state_spec.rb, spec/lib/hackney/pdf/income_preview_spec.rb, spec/models/hackney/income/models/agreement_spec.rb
We want to allow officers to create agreements for a one-off payment.
- Add `one_off` as an option for frequency in the Agreement model
- Add tests to make sure the status is updated accordingly
- Fix flaky test that failed sometimes because of float comparison
To do:
- Add one-off as an option in the frontend, need to remember to push this change to prod before the one in the frontend.
Is this all that's needed for one-off payments? 
I'm really worried I'm missing something - so please shout if I need to add anything!
https://hackney.atlassian.net/browse/MAAP-465?atlOrigin=eyJpIjoiZDFhMGNkYWU2ODc1NDFjMDkxNTNhMGIzNzdjMDVjYjgiLCJwIjoiaiJ9
=> Add one-off payment frequency

config/environments/production.rb, config/environments/staging.rb
Debug level emits lots of noise on db connections which are unnecessary to show on staging and production on a regular basis.
The application logs are stored in Papertrail, which has a data transfer cap and we've tripped the cap recently which has stopped capturing all logs in the papertrail system (including other applications.)
By default, don't emit debug logs on staging and production.
https://hackney.atlassian.net/browse/MAAP-489
=> Turn down logging on staging & prod

app/models/hackney/income_collection/letter/informal_agreement.rb, lib/hackney/pdf/income_preview.rb, lib/hackney/pdf/templates/income/informal_agreement_confirmation_letter.erb, spec/lib/hackney/pdf/income_preview_spec.rb
As a caseworker, I want to be able to send agreement confirmation letters for different payment conditions, so that I can give clear guidance to the tenant how much they need to pay.
- Allow creating variable payment agreement confirmation letter
- Allow creating one-off payment agreement confirmation letter
https://hackney.atlassian.net/browse/MAAP-488
=> Allow creating variable and one-off payment agreement confirmation letters

lib/hackney/income/migrate_uh_eviction_date.rb, spec/hackney/income/migrate_uh_eviction_date_spec.rb
we need to save eviction dates in it's own table for save keeping during sync
=> add migrate eviction date from UH usecase

app/controllers/eviction_date_response_helper.rb, app/controllers/eviction_dates_controller.rb, app/models/hackney/income/models/eviction_date.rb, config/routes.rb, db/migrate/20200915105700_create_eviction_date.rb, db/schema.rb, docs/api/v1/api.yaml, lib/hackney/income/create_eviction_date.rb, lib/hackney/income/use_case_factory.rb, spec/factories/eviction_date.rb, spec/lib/hackney/income/create_eviction_date_spec.rb, spec/models/hackney/income/models/eviction_date_spec.rb, spec/requests/eviction_dates_spec.rb
Users need to be able to add eviction dates to a tenancy through MAA, this PR creates the first endpoint to allow users to add an eviction date to our database
- Add eviction_dates table to database
- Add EvictionDate model
- Add POST create eviction date endpoint to allow an eviction date to be created
- Add CreateEvictionDate usecase
- Update API docs
Pretty similar to how we create a court case, unsure if the eviction date has all the correct fields or is missing any associations
https://hackney.atlassian.net/browse/MAAP-491
=> Add POST eviction date endpoint

lib/hackney/pdf/templates/income/informal_agreement_confirmation_letter.erb, spec/lib/hackney/pdf/income_preview_spec.rb
Ian requested a change on the wording of the `date of first payment`
- Use `date of first (monthly/weekly/etc.) payment: ` so its clear that this refers to the regular payments when there is a lump sum payment
=> Change wording for date of first payment

app/models/hackney/income_collection/letter.rb, app/models/hackney/income_collection/letter/court_date.rb, app/models/hackney/letter_date_helper.rb, lib/hackney/pdf/templates/income/court_date_letter.erb, lib/use_cases/generate_and_store_letter.rb, spec/lib/hackney/income_collection/letter_spec.rb, spec/lib/hackney/pdf/income_preview_spec.rb, spec/models/hackney/income_collection/letter/court_date_spec.rb, spec/use_cases/generate_and_store_letter_spec.rb
After an officer has added a court date and time, they want the ability to send a 'Court date letter' to remind the tenant.
- Add Court Date letter template
- Add Court Date letter model and tests to make sure the letter preview can be generated
To do:
- Hook things up in the frontend so that officers can send this letter once they add a court date and time
https://hackney.atlassian.net/browse/MAAP-485?atlOrigin=eyJpIjoiNTk3MTk5NGE1ZjVmNDFiOGE5ZjI5ZDQzNTE5MjUxMGIiLCJwIjoiaiJ9
=> Add court date letter

app/controllers/eviction_dates_controller.rb, config/routes.rb, docs/api/v1/api.yaml, lib/hackney/income/use_case_factory.rb, lib/hackney/income/view_eviction_dates.rb, spec/lib/hackney/income/view_eviction_dates_spec.rb, spec/requests/eviction_dates_spec.rb
This endpoint will allow users to view eviction dates that have been added onto a tenancy
- Add GET create eviction date endpoint to allow an eviction dates to be viewed
- Add ViewEvictionDates usecase
- Update API docs
Again pretty similar to how the court cases implementation, unsure if its possible for a tenancy to have multiple eviction dates but followed how it is done for agreements and court cases
https://hackney.atlassian.net/browse/MAAP-491
=> Add GET eviction dates endpoint

app/models/hackney/income_collection/letter/court_outcome/with_terms.rb, lib/hackney/pdf/templates/income/court_outcome_letter.erb, spec/lib/hackney/pdf/income_preview_spec.rb
We want to be able to render the payment details for formal variable payment agreements or formal one-off payment agreements when sending a court outcome letter.
- Allow rendering court outcome with variable payment agreements
- Allow rendering court outcome letter with a one-off payment agreement
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-497
=> Allow rendering court outcome letter with variable or one-off payment agreement

lib/hackney/income/tenancy_classification/helpers.rb, lib/hackney/income/tenancy_classification/helpers/helpers_base.rb, lib/hackney/income/worktray_item_gateway.rb, spec/support/shared_example_for_tenancy_classification.rb
use the sorted eviction date when classifying it
- fetch the eviction date stored in the DB while classifying and storing a worktray item 
https://hackney.atlassian.net/browse/MAAP-494
=> use stored eviction date

lib/hackney/income/tenancy_classification/rulesets/address_court_agreement_breach.rb, lib/hackney/income/tenancy_classification/rulesets/court_breach_no_payment.rb, lib/hackney/income/tenancy_classification/rulesets/send_informal_agreement_breach_letter.rb, lib/hackney/tenancy/action_codes.rb, spec/lib/hackney/income/tenancy_classification/rulesets/court_breach_no_payment_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/court_breach_visit_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_breach_letters_spec.rb, spec/support/shared_example_for_tenancy_classification.rb
The current Visit Made action can be used for other visits than court breach visits, therefore we shouldn't use this for determining the next recommended action for court breaches.
- Add a more specific Court Breach Visit Made action code in classification rules
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&projectKey=MAAP&modal=detail&selectedIssue=MAAP-520
=> Use court breach visit action code in classifier

app/models/hackney/income/models/court_case.rb, lib/hackney/income/tenancy_classification/helpers/agreement_helpers.rb, lib/hackney/income/tenancy_classification/rulesets/check_data.rb, spec/lib/hackney/income/tenancy_classification/helpers/agreement_helpers_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/check_data_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/court_breach_no_payment_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/court_breach_visit_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_breach_letters_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_informal_agreement_breach_letter_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/update_court_outcome_spec.rb, spec/lib/hackney/income/universal_housing_criteria_spec.rb, spec/models/hackney/income/models/court_cases_spec.rb, spec/support/shared_example_for_tenancy_classification.rb
Noticed while fixing a classification bug, that informal agreement breach actions could have a tighter check
- Check if the agreement is informal in `informal agreement breach?` helper
- Show `:check_data` action when the court agreement is missing
=> Tighten some of the classification rules

app/controllers/evictions_controller.rb, lib/hackney/income/create_eviction.rb, lib/hackney/income/create_eviction_and_sync.rb, lib/hackney/income/migrate_uh_eviction.rb, lib/hackney/income/use_case_factory.rb, spec/hackney/income/migrate_uh_eviction_spec.rb, spec/lib/hackney/income/create_eviction_and_sync_spec.rb
we need to resync the case when an eviction date is added so that the case could be reclassified 
added a new usecase that will save the date, add the action diary and sync the case
also fixed the eviction date migration bug https://sentry.io/organizations/london-borough-of-hackney/issues/1910471839/?project=1276456&query=is%3Aunresolved
https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=30&modal=detail&selectedIssue=MAAP-523
=> add action diary and sync after adding eviction date

lib/hackney/income/migrate_uh_agreement.rb, spec/lib/hackney/income/migrate_uh_agreement_spec.rb
There are some codes in UH that we haven't got mapped - while we should aim to add the unmapped ones, we should also be able to handle those that we do not have.
Use a case statement instead of a map, and have a default for those unknown ones.
https://sentry.io/organizations/london-borough-of-hackney/issues/1883520536/?project=1276456&query=is%3Aunresolved
=> Support unmapped uh frequency codes

app/models/hackney/income/models/court_case.rb, app/models/hackney/income_collection/letter/court_outcome.rb, lib/hackney/income/migrate_uh_court_case.rb, lib/hackney/income/tenancy_classification/classifier.rb, lib/hackney/income/tenancy_classification/helpers/court_case_helpers.rb, lib/hackney/income/tenancy_classification/rulesets/apply_for_outright_possession_warrant.rb, lib/hackney/income/update_agreement_state.rb, lib/hackney/tenancy/action_codes.rb, lib/hackney/tenancy/court_outcome_codes.rb, lib/hackney/tenancy/old_court_outcome_codes.rb, spec/factories/court_case.rb, spec/lib/hackney/income/create_court_case_spec.rb, spec/lib/hackney/income/migrate_uh_court_case_spec.rb, spec/lib/hackney/income/tenancy_classification/helpers/court_case_helpers_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/check_data_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/court_breach_no_payment_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/court_breach_visit_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_breach_letters_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/send_informal_agreement_breach_letter_spec.rb, spec/lib/hackney/income/tenancy_classification/rulesets/update_court_outcome_spec.rb, spec/lib/hackney/income/universal_housing_criteria_spec.rb, spec/lib/hackney/income/update_agreement_state_spec.rb, spec/lib/hackney/income/update_court_case_spec.rb, spec/lib/hackney/income_collection/letter_spec.rb, spec/lib/hackney/pdf/income_preview_spec.rb, spec/models/hackney/income/models/court_cases_spec.rb, spec/models/hackney/income_collection/letter/court_outcome_spec.rb, spec/requests/court_cases_spec.rb, spec/support/shared_example_for_tenancy_classification.rb
Some refactoring was needed in breach detector to reduce duplications between `UpdateAgreementState` and `CourtCase` model
- Refactor breach detector to use helper methods on court case model
- Rename UpdatedCourtOutcomeCodes to CourtOutcomeCodes## Guidance to review
The review should be the easiest commit by commit!
=> Refactoring breach detector and renaming court outcome codes

app/controllers/court_cases_controller.rb, lib/hackney/income/create_court_case.rb, lib/hackney/income/create_court_case_and_sync.rb, lib/hackney/income/use_case_factory.rb, spec/lib/hackney/income/create_court_case_and_sync_spec.rb, spec/lib/hackney/income/create_court_case_spec.rb, spec/requests/court_cases_spec.rb
When a court case is created it should be written to the action diary that one has been created and should re-sync the case
This is the first slice
- Add `add_action_diary_and_sync_case` usecase to `create_court_case` usecase to allow adding to the action diary and re-syncing when a case is created
- `court_cases_controller` now gets the username from the request
The action diary message is quite basic, is it missing anything?
https://hackney.atlassian.net/browse/MAAP-521
=> Write to action diary and sync when court case created

app/controllers/court_cases_controller.rb, app/models/hackney/court_outcome_helper.rb, lib/hackney/income/update_court_case_and_sync.rb, lib/hackney/income/use_case_factory.rb, spec/lib/hackney/income/update_court_case_and_sync_spec.rb, spec/requests/court_cases_spec.rb
When an officer adds a court outcome, we want an entry to be added to the action diary and the case to be synced.
- Created new UpdateCourtCaseAndSync use case
- Implements the UpdateCourtCase and AddActionDiaryAndSyncCase
- This was created because those two use cases have a circular dependency, which this new use case avoids
- Make Court Case Controller use this new use case for the Court Case Update endpoint
There is some refactoring to be done court_cases_spec.rb, which I will try and do now.
I'm still not 100% confident when it comes to RSpec and test doubles so please shout if my use of them in the two tests doesn't make sense!
https://hackney.atlassian.net/browse/MAAP-522?atlOrigin=eyJpIjoiMmQ0OTczMDEzNjY4NGE3OTg5NTZlYmUxNGRhNDMyYjYiLCJwIjoiaiJ9
=> Add action diary entry and sync when adding a court outcome

spec/lib/hackney/income/create_court_case_and_sync_spec.rb
To fix tests failing on master, the tests for the `create_court_case_and_sync` usecase needed to reference the correct court outcome codes file
- Use correct `CourtOutcomeCodes` file for tests
=> Use correct court outcome codes file for court case add action diary & sync test

lib/hackney/income/migrate_uh_court_case.rb, spec/lib/hackney/income/migrate_uh_court_case_spec.rb
Errors have been popping up on sentry detecting that syncing UH court cases has been failing as the update_court_case
usecase was missing its keyword arguments thus stopping the migration from running. I am unsure why the original implementation did not work as the current version of ruby the application uses allows a double splat operator to be used within a keyword argument
- explicitly pass in court_case_params into update_cout_case usecase
I am unsure if this is the best way of going round that issue due to not understanding the nitty gritty of the language but due to time constraints, it would be best to discuss this in the future.
https://hackney.atlassian.net/browse/MAAP-533
=> Update UH court case migration to explicitly pass in court_case_params
